import { resolvePath } from "@typespec/compiler";
import { createTester } from "@typespec/compiler/testing";

export const Tester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@specgen/emitter-typescript"],
})
  .importLibraries()
  .using("Http");

export function emitter(options: Record<string, unknown> = {}) {
  return Tester.emit("@specgen/emitter-typescript", options);
}

export const HEADER = "// Code generated by @specgen/emitter-typescript. DO NOT EDIT.";
