import { resolvePath } from "@typespec/compiler";
import { createTester } from "@typespec/compiler/testing";

export const Tester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@abhigyakrishna/tspgen-core", "@abhigyakrishna/tspgen-typescript"],
})
  .importLibraries()
  .using("Http");

export function emitter(options: Record<string, unknown> = {}) {
  return Tester.emit("@abhigyakrishna/tspgen-typescript", options);
}

export const HEADER = "// Code generated by @abhigyakrishna/tspgen-typescript. DO NOT EDIT.";

/** Tester with the optional SSE libraries (`@typespec/streams`, `@typespec/events`, `@typespec/sse`). */
export const SseTester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: [
    "@typespec/http",
    "@typespec/streams",
    "@typespec/events",
    "@typespec/sse",
    "@abhigyakrishna/tspgen-core",
    "@abhigyakrishna/tspgen-typescript",
  ],
})
  .importLibraries()
  .using("Http", "SSE", "Events");
