/**
 * `text` as line comments: every line prefixed with `prefix` and a space; blank lines get the bare prefix. A
 * trailing newline (e.g. YAML's `header-text: |` block scalar) is dropped rather than becoming a stray blank
 * comment line, and `\r\n` line endings are normalized to `\n`.
 */
export function lineComments(text: string, prefix: string): string {
  return text
    .replace(/(\r?\n)+$/, "")
    .split(/\r?\n/)
    .map((line) => (line ? `${prefix} ${line}` : prefix))
    .join("\n");
}

/** Default header banner text for a language emitter (`features.header`, overridden by `header-text`). */
export function defaultHeaderText(emitter: string): string {
  return `Code generated by ${emitter}. DO NOT EDIT.`;
}
