import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { typecheck } from "./typecheck.js";
import { nextjs, petSpec } from "./tester.js";

const SHIPYARD_FLAGS = {
  exactOptionalPropertyTypes: true,
  noUncheckedIndexedAccess: true,
  noImplicitOverride: true,
  noFallthroughCasesInSwitch: true,
};
const ENV = { "env.d.ts": "declare const process: { env: Record<string, string | undefined> };\n" };
const HEADER = "// Code generated by @abhigyakrishna/tspgen-typescript. DO NOT EDIT.";

export const authSpec = `
  @service @useAuth(BearerAuth) namespace Shop;
  model Key is ApiKeyAuth<ApiKeyLocation.query, "api-key">;
  model Session is ApiKeyAuth<ApiKeyLocation.cookie, "sid">;
  model \`x-partner\` is ApiKeyAuth<ApiKeyLocation.header, "X-Partner">;
  model Item { name: string }
  @route("/items") interface Items {
    @get list(@query q?: string): Item[];
    @post @useAuth(NoAuth) create(@body item: Item): void;
    @get @route("/basic") @useAuth(BasicAuth | Key | NoAuth) either(): void;
    @get @route("/both") @useAuth([Session, \`x-partner\`]) both(@cookie theme?: string): void;
  }
`;

const flatSpec = authSpec.replace("@cookie theme?: string", "");

describe("grouped client auth", () => {
  it("declares <Service>Auth and types the factory's config with it", async () => {
    const { outputs } = await nextjs({ features: { "react-query": false, "server-actions": false } }).compile(authSpec);
    expect(outputs["client/index.ts"]).toBe(`${HEADER}
import type { AuthProvider, BasicCredentials, ClientConfig } from "./core";
import { ItemsClient } from "./items";

export * from "./core";
export * from "./items";

/** Credential providers of the Shop API, by auth scheme id (\`auth\` in the client config). */
export interface ShopAuth {
  /** Bearer token, sent as \`Authorization: Bearer …\`. */
  BearerAuth?: AuthProvider<string>;
  /** Username and password, sent as \`Authorization: Basic …\`. */
  BasicAuth?: AuthProvider<BasicCredentials>;
  /** API key, sent as the \`api-key\` query parameter. */
  Key?: AuthProvider<string>;
  /** API key, sent as the \`sid\` cookie. */
  Session?: AuthProvider<string>;
  /** API key, sent as the \`X-Partner\` header. */
  "x-partner"?: AuthProvider<string>;
}

/** Entry point for the Shop API. */
export class ShopApiClient {
  readonly items: ItemsClient;

  constructor(config: ClientConfig<ShopAuth>) {
    this.items = new ItemsClient(config);
  }
}

export function createShopClient(config: ClientConfig<ShopAuth>): ShopApiClient {
  return new ShopApiClient(config);
}
`);
  });

  it("gives each operation its auth descriptor; NoAuth-only operations get none", async () => {
    const { outputs } = await nextjs({ features: { "react-query": false, "server-actions": false } }).compile(authSpec);
    const items = outputs["client/items.ts"];
    expect(items).toContain(`        path: "/items",
        query: [["q", params.q, false]],
        auth: [[{ id: "BearerAuth", kind: "bearer" }]],
      },`);
    expect(items).toContain(`        body: params.item,
        contentType: "application/json",
      },`);
    expect(items).toContain(
      `        auth: [[{ id: "BasicAuth", kind: "basic" }], [{ id: "Key", kind: "apiKey", in: "query", name: "api-key" }]],`,
    );
    expect(items).toContain(
      `        cookies: { theme: params.theme },
        auth: [[{ id: "Session", kind: "apiKey", in: "cookie", name: "sid" }, { id: "x-partner", kind: "apiKey", in: "header", name: "X-Partner" }]],`,
    );
  });

  it("exports only AuthScheme from core; the auth runtime stays module-private", async () => {
    const { outputs } = await nextjs({ features: { "react-query": false, "server-actions": false } }).compile(authSpec);
    const core = outputs["client/core.ts"];
    expect(core).toContain("export interface AuthScheme {");
    expect(core).toContain("\ninterface AuthEntries {");
    expect(core).toContain("\nasync function resolveAuth(");
    expect(core).not.toMatch(/export (interface AuthEntries|async function resolveAuth|function base64)/);
  });

  it("types the Server Actions' configuration with <Service>Auth", async () => {
    const { outputs } = await nextjs().compile(authSpec);
    const server = outputs["client/actions/server-client.ts"];
    expect(server).toContain('import type { ShopAuth } from "../index";');
    expect(server).toContain("let shopServerClientOverrides: Partial<ClientConfig<ShopAuth>> = {};");
    expect(server).toContain("export function configureShopActions(config: Partial<ClientConfig<ShopAuth>>): void {");
  });

  it("type-checks under shipyard's compiler flags, with and without zod", async () => {
    for (const zod of [false, true]) {
      const { outputs } = await nextjs({}, { features: { zod } }).compile(authSpec);
      const usage = `import { createShopClient } from "./client/index";
export const api = createShopClient({
  baseUrl: "/api",
  auth: {
    BearerAuth: async () => "token",
    BasicAuth: () => ({ username: "u", password: "p" }),
    "x-partner": () => undefined,
  },
});
// @ts-expect-error unknown scheme id
createShopClient({ baseUrl: "/api", auth: { Nope: () => "x" } });
`;
      expect(typecheck({ ...outputs, ...ENV, "usage.ts": usage }, SHIPYARD_FLAGS)).toBe("");
    }
  });

  it("warns about unsupported http schemes and drops the alternatives needing them", async () => {
    const [{ outputs }, diagnostics] = await nextjs({ features: { "react-query": false, "server-actions": false } }).compileAndDiagnose(`
      @service namespace S;
      model Digest { type: AuthType.http; scheme: "Digest" }
      @route("/a") interface A {
        @get @useAuth(Digest | BearerAuth) a(): void;
        @get @route("/d") @useAuth(Digest) d(): void;
      }
    `);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-core/unsupported-auth-scheme",
      severity: "warning",
      message: "Auth scheme 'Digest' (http Digest) is not supported by the Next.js client; alternatives needing it are ignored.",
    });
    // The warning points at the scheme model.
    expect(diagnostics[0]?.target).toMatchObject({ kind: "Model", name: "Digest" });
    expect(outputs["client/a.ts"]).toContain(`        path: "/a",\n        auth: [[{ id: "BearerAuth", kind: "bearer" }]],`);
    expect(outputs["client/a.ts"]).toContain(`        path: "/a/d",\n      },`);
    expect(outputs["client/index.ts"]).not.toContain("Digest");
  });

  it("warns when one alternative sends two credentials as the same header", async () => {
    for (const flat of [false, true]) {
      const [, diagnostics] = await nextjs(flat ? { "client-style": "flat" } : { features: { "react-query": false, "server-actions": false } }).compileAndDiagnose(`
        @service namespace S;
        model Auth2 is ApiKeyAuth<ApiKeyLocation.header, "authorization">;
        model K1 is ApiKeyAuth<ApiKeyLocation.header, "X-Key">;
        model K2 is ApiKeyAuth<ApiKeyLocation.header, "x-key">;
        model Q is ApiKeyAuth<ApiKeyLocation.query, "X-Key">;
        @route("/a") interface A {
          @get @useAuth([BearerAuth, BasicAuth]) a(): void;
          @get @route("/b") @useAuth([BearerAuth, Auth2] | BasicAuth) b(): void;
          @get @route("/c") @useAuth([K1, K2]) c(): void;
          @get @route("/d") @useAuth(BearerAuth | BasicAuth | [K1, Q]) d(): void;
        }
      `);
      const target = flat ? "the flat client" : "the Next.js client";
      expectDiagnostics(diagnostics, [
        ["S.A.a", "authorization", "BearerAuth, BasicAuth"],
        ["S.A.b", "authorization", "BearerAuth, Auth2"],
        ["S.A.c", "x-key", "K1, K2"],
      ].map(([op, header, schemes]) => ({
        code: "@abhigyakrishna/tspgen-typescript/auth-header-conflict",
        severity: "warning" as const,
        message: `Operation '${op}' sends several credentials (${schemes}) as the '${header}' header in one auth alternative; ${target} sends only the last one.`,
      })));
    }
  });

  it("emits no auth code for services with NoAuth only or without @useAuth", async () => {
    const { outputs } = await nextjs().compile(`@service @useAuth(NoAuth) namespace S; @route("/a") op a(): void;`);
    for (const content of Object.values(outputs)) expect(content).not.toMatch(/AuthProvider|AuthScheme|resolveAuth|ClientConfig<|auth:/);
    const plain = await nextjs().compile(petSpec);
    for (const [path, content] of Object.entries(plain.outputs)) {
      expect(content, path).not.toMatch(/AuthProvider|AuthScheme|resolveAuth|ClientConfig</);
    }
  });
});

describe("flat client auth", () => {
  const flat = { "client-style": "flat" };

  it("declares <Service>Auth and passes each operation's descriptor to request()", async () => {
    const { outputs } = await nextjs(flat).compile(flatSpec);
    const client = outputs["client.ts"];
    expect(client).toContain(`/** \`Auth\`: the client's \`<Service>Auth\` credential providers. */
export interface ClientOptions<Auth extends object = object> {`);
    expect(client).toContain(`export interface ShopAuth {
  /** Bearer token, sent as \`Authorization: Bearer …\`. */
  BearerAuth?: () => string | undefined | Promise<string | undefined>;
  /** Username and password, sent as \`Authorization: Basic …\`. */
  BasicAuth?: () => { username: string; password: string } | undefined | Promise<{ username: string; password: string } | undefined>;
  /** API key, sent as the \`api-key\` query parameter. */
  Key?: () => string | undefined | Promise<string | undefined>;
  /** API key, sent as the \`sid\` cookie. */
  Session?: () => string | undefined | Promise<string | undefined>;
  /** API key, sent as the \`X-Partner\` header. */
  "x-partner"?: () => string | undefined | Promise<string | undefined>;
}

export class ShopClient {
  private readonly baseUrl: string;
  private readonly doFetch: typeof fetch;
  private readonly headers: Record<string, string>;
  private readonly auth: ShopAuth | undefined;

  constructor(options: ClientOptions<ShopAuth>) {`);
    expect(client).toContain(`    return this.send("GET", \`/items\${toQuery(query)}\`, undefined, init, [[{ id: "BearerAuth", kind: "bearer" }]]);`);
    expect(client).toContain(`    await this.request("POST", "/items", item, init);`);
  });

  it("type-checks under shipyard's compiler flags, per-type and single-file", async () => {
    for (const layout of ["per-type", "single-file"]) {
      const { outputs } = await nextjs(flat, { layout }).compile(flatSpec);
      const usage = `import { ShopClient } from "./index";
export const api = new ShopClient({ baseUrl: "/api", auth: { BearerAuth: async () => "t", Key: () => undefined } });
`;
      expect(typecheck({ ...outputs, "usage.ts": usage }, SHIPYARD_FLAGS)).toBe("");
    }
  });

  it("reports generated types named like <Service>Auth or the auth helpers as clashes", async () => {
    for (const [name, messageId] of [["ShopAuth", undefined], ["AuthScheme", "local"], ["AuthEntries", "local"]] as const) {
      const [, diagnostics] = await nextjs(flat).compileAndDiagnose(`${flatSpec}\nmodel ${name} { x: string } @route("/n") op n(): ${name};`);
      expectDiagnostics(diagnostics, {
        code: "@abhigyakrishna/tspgen-typescript/flat-client-name-clash",
        message: messageId ? /internally/ : /own export/,
      });
    }
    // Without @useAuth those names are free.
    const [, diagnostics] = await nextjs(flat).compileAndDiagnose(
      `@service namespace S; model ShopAuth { x: string } model AuthScheme { y: string } @route("/n") op n(): ShopAuth | AuthScheme;`,
    );
    expectDiagnostics(diagnostics, []);
  });

  it("rejects an operation named auth only when the client has auth", async () => {
    const [, diagnostics] = await nextjs(flat).compileAndDiagnose(`@service @useAuth(BearerAuth) namespace S; @route("/a") op auth(): void;`);
    expectDiagnostics(diagnostics, { code: "@abhigyakrishna/tspgen-typescript/flat-client-unsupported", message: /client member/ });
    const [, clean] = await nextjs(flat).compileAndDiagnose(`@service namespace S; @route("/a") op auth(): void;`);
    expectDiagnostics(clean, []);
  });
});
