import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { nextjs } from "./tester.js";
import { typecheck } from "./typecheck.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-typescript. DO NOT EDIT.";

const SHIPYARD_FLAGS = {
  exactOptionalPropertyTypes: true,
  noUncheckedIndexedAccess: true,
  noImplicitOverride: true,
  noFallthroughCasesInSwitch: true,
};

export const rqSpec = `
  using TspGen;
  @service namespace Shop;
  model ErrorResponse { status: int32; code: string; message: string }
  namespace Graph {
    enum Kind { DATABASE, QUEUE }
    model Node { id: string; kind: Kind }
    model CreateNodeRequest { name: string }
    model Patch { name?: string }
    @route("/graph/nodes") interface Nodes {
      /** Lists nodes. */
      @get listNodes(@query kind?: Kind, @query limit?: int32): Node[];
      @get @route("/{id}") readNode(
        /** The node id. */
        @path id: string,
      ): Node;
      @get @route("/search") search(@query text: string, @query limit?: int32): Node[];
      @get @route("/count") count(): { total: int32 };
      @put @route("/{id}") updateNode(@path id: string, @body body: CreateNodeRequest, @query dryRun?: boolean): Node;
      @patch @route("/{id}") patchNode(@path id: string, @body patch?: Patch, @query reason: string): Node;
      @post @route("/refresh") refresh(): void;
    }
    @route("/avatars") interface Avatars {
      @put @route("/{id}") uploadAvatar(@path id: string, @bodyRoot file: File<"image/png">): void;
    }
  }
  @@meta(Shop.Graph.Nodes.readNode, "typescript:ts-nextjs-client", #{ staleTime: 30000 });
`;

const flat = { "client-style": "flat", "error-model": "ErrorResponse", "react-query": true };
const house = { layout: "single-file", errors: "thrown" };

/** A consumer of the generated hooks, type-checked with them (exercises Vars under exactOptionalPropertyTypes). */
const usage = `import { QueryClient } from "@tanstack/react-query";
import { ShopClient, shopKeys, shopQueries, type Node } from "./index";
import { ShopClientProvider, useCountQuery, useListNodesQuery, usePatchNodeMutation, useReadNodeQuery, useRefreshMutation, useSearchQuery, useUpdateNodeMutation, useUploadAvatarMutation } from "./hooks";

const client = new ShopClient({ baseUrl: "/api" });
export const provider = ShopClientProvider({ client, children: null });
export async function prefetch(queryClient: QueryClient): Promise<Node> {
  await queryClient.invalidateQueries({ queryKey: shopKeys.nodes.all });
  return queryClient.fetchQuery(shopQueries.nodes.readNode(client, { id: "1" }));
}
export function Component(): void {
  const all: Node[] | undefined = useListNodesQuery().data;
  const some = useListNodesQuery({ query: { kind: "DATABASE" } }, { enabled: all !== undefined });
  const one: Node | undefined = useReadNodeQuery({ id: "1" }, { select: (n) => n }).data;
  useSearchQuery({ query: { text: "db" } });
  // @ts-expect-error required query object
  useSearchQuery({});
  const total: number | undefined = useCountQuery({ enabled: false }).data?.total;
  useUpdateNodeMutation().mutate({ id: "1", body: { name: "n" } });
  usePatchNodeMutation({ onSuccess: (n: Node) => n }).mutate({ id: "1", query: { reason: "r" } });
  // @ts-expect-error exactOptionalPropertyTypes: omit the key instead
  usePatchNodeMutation().mutate({ id: "1", body: undefined, query: { reason: "r" } });
  useRefreshMutation().mutate();
  useUploadAvatarMutation().mutate({ id: "1", body: new Blob([]) });
  void [some, one, total];
}
`;

describe("flat client react-query", () => {
  it("emits Vars, keys and queryOptions in a server-safe queries.ts", async () => {
    const { outputs } = await nextjs(flat, house).compile(rqSpec);
    expect(outputs["queries.ts"]).toBe(QUERIES);
  });

  it("emits the provider and hooks in a use-client hooks.ts", async () => {
    const { outputs } = await nextjs(flat, house).compile(rqSpec);
    expect(outputs["hooks.ts"]).toBe(HOOKS);
  });

  it("re-exports queries.ts, not hooks.ts, from index.ts", async () => {
    const { outputs } = await nextjs(flat, house).compile(rqSpec);
    expect(outputs["index.ts"]).toBe(`${HEADER}

export * from "./client";
export * from "./queries";
export * from "./types";
`);
  });

  it("is off by default for the flat client", async () => {
    for (const options of [{ "client-style": "flat" }, { "client-style": "flat", "react-query": false }]) {
      const [result, diagnostics] = await nextjs(options, house).compileAndDiagnose(rqSpec);
      expect(diagnostics).toEqual([]);
      expect(Object.keys(result.outputs).filter((k) => k.includes("queries") || k.includes("hooks"))).toEqual([]);
      expect(result.outputs["index.ts"]).not.toContain("queries");
    }
  });

  it("type-checks with a consumer under shipyard's flags, per-type, single-file, with and without validate", async () => {
    const combos: [Record<string, unknown>, boolean][] = [
      [house, false],
      [{}, false],
      [{ ...house, zod: true }, true],
      [{ zod: true }, true],
    ];
    for (const [emitterOptions, validate] of combos) {
      const { outputs } = await nextjs({ ...flat, validate }, emitterOptions).compile(rqSpec);
      expect(typecheck({ ...outputs, "usage.ts": usage }, SHIPYARD_FLAGS)).toBe("");
    }
  });

  it("type-checks with the models in their own output dir", async () => {
    const { outputs } = await nextjs({ ...flat, "output-dir": "{emitter-output-dir}/web" }, { ...house, "models-output-dir": "{emitter-output-dir}/shared" }).compile(rqSpec);
    expect(outputs["web/queries.ts"]).toContain(`import type { CreateNodeRequest, Kind, Patch } from "../shared/types";`);
    expect(outputs["web/hooks.ts"]).toContain(`import type { CountResponse, Node } from "../shared/types";`);
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("omits unused TanStack imports when a client has only queries or only mutations", async () => {
    const spec = `
      @service namespace Reads { model R { a: string } @route("/r") op read(): R; }
    `;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(spec);
    expect(outputs["hooks.ts"]).not.toContain("useMutation");
    expect(typecheck(outputs, { ...SHIPYARD_FLAGS, noUnusedLocals: true })).toBe("");
    const writes = `@service namespace Writes { @route("/w") @post op write(@query force?: boolean): void; }`;
    const w = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(writes);
    expect(w.outputs["queries.ts"]).not.toContain("queryOptions");
    expect(w.outputs["queries.ts"]).toContain(`export const writesQueries = {\n};`);
    expect(w.outputs["hooks.ts"]).not.toContain("useQuery");
    expect(w.outputs["hooks.ts"]).toContain("mutationFn: (vars: WriteVars) => client.write(vars.query)");
    expect(typecheck(w.outputs, { ...SHIPYARD_FLAGS, noUnusedLocals: true })).toBe("");
  });

  it("keys Vars by the public parameter names when validate renames z inside the method", async () => {
    const spec = `using TspGen;
      @service namespace Maps;
      model Tile { data: string }
      model Z { v: string }
      @route("/tiles") interface Tiles {
        @get @route("/{z}/{x}/{y}") tile(@path z: int32, @path x: int32, @path y: int32, @query format?: string): Tile;
        @post @route("/{id}") put(@path id: string, @body z: Z): void;
      }`;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true, validate: true }, { ...house, zod: true }).compile(spec);
    expect(outputs["client.ts"]).toContain("  async tile(zValue: number, x: number, y: number, query: { format?: string } = {}, init?: { signal?: AbortSignal }): Promise<Tile> {");
    expect(outputs["queries.ts"]).toContain(`export interface TileVars {
  z: number;
  x: number;
  y: number;
  /**
   * Query parameters.
   */
  query?: { format?: string };
}`);
    expect(outputs["queries.ts"]).toContain("queryFn: ({ signal }) => client.tile(vars.z, vars.x, vars.y, vars.query, { signal }),");
    expect(outputs["hooks.ts"]).toContain("mutationFn: (vars: PutVars) => client.put(vars.id, vars.body)");
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("keeps a path parameter named init as a Vars key (the method's init parameter is renamed)", async () => {
    const spec = `@service namespace S; model N { a: string }
      @route("/n/{init}") @get op readN(@path \`init\`: string): N;`;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(spec);
    expect(outputs["client.ts"]).toContain("  readN(init: string, requestInit?: { signal?: AbortSignal }): Promise<N> {");
    expect(outputs["queries.ts"]).toContain("export interface ReadNVars {\n  init: string;\n}");
    expect(outputs["queries.ts"]).toContain("queryFn: ({ signal }) => client.readN(vars.init, { signal }),");
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("skips React Query code for an operation whose path parameter collides with the body or query Vars key", async () => {
    const cases: [string, string, string][] = [
      [`@route("/b/{body}") @post op postB(@path body: string, @body payload: N): void;`, "S.postB", "body"],
      [`@route("/q/{query}") @get op getQ(@path query: string, @query limit?: int32): N;`, "S.getQ", "query"],
    ];
    for (const [op, id, key] of cases) {
      const spec = `@service namespace S; model N { a: string }\n@route("/n") op readN(): N;\n${op}`;
      const [result, diagnostics] = await nextjs({ "client-style": "flat", "react-query": true }, house).compileAndDiagnose(spec);
      expectDiagnostics(diagnostics, {
        code: "@abhigyakrishna/tspgen-typescript/flat-react-query-skipped",
        severity: "warning",
        message: `Operation '${id}' gets no React Query hooks, keys or Vars: path parameter '${key}' clashes with the '${key}' key of its React Query variables.`,
      });
      const name = id.slice(2);
      const pascal = name[0]!.toUpperCase() + name.slice(1);
      // the client method is still generated, the other operations keep their hooks
      expect(result.outputs["client.ts"]).toMatch(new RegExp(`\\n  (async )?${name}\\(${key}: string, `));
      expect(result.outputs["hooks.ts"]).toContain("export function useReadNQuery(");
      for (const file of ["queries.ts", "hooks.ts"]) expect(result.outputs[file]).not.toContain(pascal);
      expect(result.outputs["queries.ts"]).not.toContain(`${name}:`);
      expect(typecheck(result.outputs, { ...SHIPYARD_FLAGS, noUnusedLocals: true })).toBe("");
      // without react-query there is nothing to skip
      const [, plain] = await nextjs({ "client-style": "flat" }, house).compileAndDiagnose(spec);
      expect(plain).toEqual([]);
    }
  });

  it("keys Vars by the public name of a path parameter or body named like a reserved word", async () => {
    const spec = `@service namespace S; model N { a: string }
      @route("/c/{class}") @post op postClass(@path \`class\`: string, @body \`default\`: N): N;`;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(spec);
    expect(outputs["client.ts"]).toContain(
      '  postClass(classValue: string, defaultValue: N, init?: { signal?: AbortSignal }): Promise<N> {\n    return this.send("POST", `/c/${encodeURIComponent(String(classValue))}`, defaultValue, init);',
    );
    expect(outputs["queries.ts"]).toContain("export interface PostClassVars {\n  class: string;\n");
    expect(outputs["hooks.ts"]).toContain("mutationFn: (vars: PostClassVars) => client.postClass(vars.class, vars.body)");
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("documents Vars body and query and marks keys and queries of deprecated operations", async () => {
    const spec = `@service namespace S; model N { a: string }
      @route("/n") interface Ns {
        #deprecated "use readN"
        @get @route("/old") oldN(@query limit?: int32): N;
        @get readN(): N;
        @post create(
          /** The node to create. */
          @body node: N,
          @query dryRun?: boolean,
        ): N;
      }`;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(spec);
    expect(outputs["queries.ts"]).toContain(`export interface CreateVars {
  /**
   * The node to create.
   */
  body: N;
  /**
   * Query parameters.
   */
  query?: { dryRun?: boolean };
}`);
    expect(outputs["queries.ts"]).toContain(`    /**
     * @deprecated use readN
     */
    oldN: (vars: OldNVars = {}) => ["S", "ns", "oldN", vars] as const,
    readN: () => ["S", "ns", "readN"] as const,`);
    expect(outputs["queries.ts"]).toContain(`    /**
     * @deprecated use readN
     */
    oldN: (client: SClient, vars: OldNVars = {}) =>`);
    expect(outputs["hooks.ts"]).toContain(`/**
 * @deprecated use readN
 */
export function useOldNQuery(`);
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("resolves void GET/HEAD queries to null", async () => {
    const spec = `@service namespace S;
      @route("/n") interface Ns {
        @head @route("/{id}") exists(@path id: string): void;
      }`;
    const { outputs } = await nextjs({ "client-style": "flat", "react-query": true }, house).compile(spec);
    expect(outputs["queries.ts"]).toContain(`    exists: (client: SClient, vars: ExistsVars) =>
      queryOptions({
        queryKey: sKeys.ns.exists(vars),
        queryFn: async ({ signal }) => {
          await client.exists(vars.id, { signal });
          return null;
        },
      }),`);
    expect(outputs["hooks.ts"]).toContain(
      `  options?: Omit<UseQueryOptions<null, Error, null, ReturnType<typeof sKeys.ns.exists>>, "queryKey" | "queryFn">,`,
    );
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("reports hooks, Vars and keys generated twice across services or groups", async () => {
    const cases: [string, string, string, string][] = [
      [
        `@service namespace A { model N { a: string } @route("/a") op readNode(): N; }
         @service namespace B { model M { b: string } @route("/b") op readNode(@query q?: string): M; }`,
        "A.readNode",
        "B.readNode",
        "useReadNodeQuery",
      ],
      [
        `@service namespace A { @route("/a") interface Nodes { @get all(): void; } }`,
        "A.Nodes",
        "A.Nodes.all",
        "aKeys.nodes.all",
      ],
      [`@service namespace A { @route("/a") interface All { @get list(): void; } }`, "A", "A.All", "aKeys.all"],
    ];
    for (const [spec, first, second, name] of cases) {
      const [result, diagnostics] = await nextjs({ "client-style": "flat", "react-query": true }, house).compileAndDiagnose(spec);
      expectDiagnostics(diagnostics, {
        code: "@abhigyakrishna/tspgen-typescript/flat-react-query-name-clash",
        message: `'${first}' and '${second}' both generate '${name}' in the flat client's React Query code; rename one (e.g. @TS.name).`,
      });
      expect(result.outputs["client.ts"]).toBeUndefined();
    }
  });

  it("reports generated types named like the React Query exports or the names its files use", async () => {
    const cases: [string, string, boolean][] = [
      ["ReadNodeVars", "ReadNodeVars", true],
      ["useReadNodeQuery", "useReadNodeQuery", true],
      ["shopKeys", "shopKeys", true],
      ["ShopClientProvider", "ShopClientProvider", true],
      ["queryOptions", "queryOptions", false],
      ["UseQueryOptions", "UseQueryOptions", false],
      ["ReactNode", "ReactNode", false],
      ["ShopClientContext", "ShopClientContext", false],
    ];
    for (const [tsName, name, exported] of cases) {
      const spec = `${rqSpec}\n@TS.name("${tsName}") model Clash { x: string }`;
      const [result, diagnostics] = await nextjs(flat, house).compileAndDiagnose(spec);
      expectDiagnostics(diagnostics, {
        code: "@abhigyakrishna/tspgen-typescript/flat-client-name-clash",
        message: exported
          ? `Generated type '${name}' clashes with the flat client's own export; rename it with @TS.name or set error-class.`
          : `Generated type '${name}' clashes with a name the flat client uses internally ('${name}'); rename it with @TS.name.`,
      });
      expect(result.outputs["client.ts"]).toBeUndefined();
      // these names are free without react-query
      const [, plain] = await nextjs({ ...flat, "react-query": false }, house).compileAndDiagnose(spec);
      expect(plain).toEqual([]);
    }
  });

  it("still rejects server-actions for the flat client", async () => {
    const diagnostics = await nextjs({ ...flat, "server-actions": true }, house).diagnose(rqSpec);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-typescript/unsupported-in-flat-style",
      message: `Option 'server-actions' is not supported with client-style "flat".`,
    });
  });
});

const QUERIES = `${HEADER}
import { queryOptions } from "@tanstack/react-query";
import type { ShopClient } from "./client";
import type { CreateNodeRequest, Kind, Patch } from "./types";

export interface ListNodesVars {
  /**
   * Query parameters.
   */
  query?: { kind?: Kind; limit?: number };
}

export interface ReadNodeVars {
  /**
   * The node id.
   */
  id: string;
}

export interface SearchVars {
  /**
   * Query parameters.
   */
  query: { text: string; limit?: number };
}

export interface UpdateNodeVars {
  id: string;
  body: CreateNodeRequest;
  /**
   * Query parameters.
   */
  query?: { dryRun?: boolean };
}

export interface PatchNodeVars {
  id: string;
  body?: Patch;
  /**
   * Query parameters.
   */
  query: { reason: string };
}

export interface UploadAvatarVars {
  id: string;
  body: globalThis.Blob;
}

export const shopKeys = {
  all: ["Shop"] as const,
  nodes: {
    all: ["Shop", "nodes"] as const,
    listNodes: (vars: ListNodesVars = {}) => ["Shop", "nodes", "listNodes", vars] as const,
    readNode: (vars: ReadNodeVars) => ["Shop", "nodes", "readNode", vars] as const,
    search: (vars: SearchVars) => ["Shop", "nodes", "search", vars] as const,
    count: () => ["Shop", "nodes", "count"] as const,
  },
  avatars: {
    all: ["Shop", "avatars"] as const,
  },
};

export const shopQueries = {
  nodes: {
    listNodes: (client: ShopClient, vars: ListNodesVars = {}) =>
      queryOptions({
        queryKey: shopKeys.nodes.listNodes(vars),
        queryFn: ({ signal }) => client.listNodes(vars.query, { signal }),
      }),
    readNode: (client: ShopClient, vars: ReadNodeVars) =>
      queryOptions({
        queryKey: shopKeys.nodes.readNode(vars),
        queryFn: ({ signal }) => client.readNode(vars.id, { signal }),
        staleTime: 30000,
      }),
    search: (client: ShopClient, vars: SearchVars) =>
      queryOptions({
        queryKey: shopKeys.nodes.search(vars),
        queryFn: ({ signal }) => client.search(vars.query, { signal }),
      }),
    count: (client: ShopClient) =>
      queryOptions({
        queryKey: shopKeys.nodes.count(),
        queryFn: ({ signal }) => client.count({ signal }),
      }),
  },
};
`;

const HOOKS = `${HEADER}
"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import type { UseMutationOptions, UseQueryOptions } from "@tanstack/react-query";
import { createContext, createElement, useContext } from "react";
import type { ReactNode } from "react";
import type { ShopClient } from "./client";
import { shopKeys, shopQueries } from "./queries";
import type { ListNodesVars, PatchNodeVars, ReadNodeVars, SearchVars, UpdateNodeVars, UploadAvatarVars } from "./queries";
import type { CountResponse, Node } from "./types";

const ShopClientContext = createContext<ShopClient | null>(null);

/** Makes a ShopClient available to the generated hooks. */
export function ShopClientProvider(props: { client: ShopClient; children?: ReactNode }): ReactNode {
  return createElement(ShopClientContext.Provider, { value: props.client }, props.children);
}

export function useShopClient(): ShopClient {
  const client = useContext(ShopClientContext);
  if (!client) throw new Error("ShopClientProvider is missing");
  return client;
}

/**
 * Lists nodes.
 */
export function useListNodesQuery(
  vars: ListNodesVars = {},
  options?: Omit<UseQueryOptions<Node[], Error, Node[], ReturnType<typeof shopKeys.nodes.listNodes>>, "queryKey" | "queryFn">,
) {
  const client = useShopClient();
  return useQuery({ ...shopQueries.nodes.listNodes(client, vars), ...options });
}

export function useReadNodeQuery(
  vars: ReadNodeVars,
  options?: Omit<UseQueryOptions<Node, Error, Node, ReturnType<typeof shopKeys.nodes.readNode>>, "queryKey" | "queryFn">,
) {
  const client = useShopClient();
  return useQuery({ ...shopQueries.nodes.readNode(client, vars), ...options });
}

export function useSearchQuery(
  vars: SearchVars,
  options?: Omit<UseQueryOptions<Node[], Error, Node[], ReturnType<typeof shopKeys.nodes.search>>, "queryKey" | "queryFn">,
) {
  const client = useShopClient();
  return useQuery({ ...shopQueries.nodes.search(client, vars), ...options });
}

export function useCountQuery(
  options?: Omit<UseQueryOptions<CountResponse, Error, CountResponse, ReturnType<typeof shopKeys.nodes.count>>, "queryKey" | "queryFn">,
) {
  const client = useShopClient();
  return useQuery({ ...shopQueries.nodes.count(client), ...options });
}

export function useUpdateNodeMutation(
  options?: Omit<UseMutationOptions<Node, Error, UpdateNodeVars>, "mutationFn">,
) {
  const client = useShopClient();
  return useMutation({ ...options, mutationFn: (vars: UpdateNodeVars) => client.updateNode(vars.id, vars.body, vars.query) });
}

export function usePatchNodeMutation(
  options?: Omit<UseMutationOptions<Node, Error, PatchNodeVars>, "mutationFn">,
) {
  const client = useShopClient();
  return useMutation({ ...options, mutationFn: (vars: PatchNodeVars) => client.patchNode(vars.id, vars.body, vars.query) });
}

export function useRefreshMutation(
  options?: Omit<UseMutationOptions<void, Error, void>, "mutationFn">,
) {
  const client = useShopClient();
  return useMutation({ ...options, mutationFn: () => client.refresh() });
}

export function useUploadAvatarMutation(
  options?: Omit<UseMutationOptions<void, Error, UploadAvatarVars>, "mutationFn">,
) {
  const client = useShopClient();
  return useMutation({ ...options, mutationFn: (vars: UploadAvatarVars) => client.uploadAvatar(vars.id, vars.body) });
}
`;
