import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { nextjs } from "./tester.js";
import { typecheck } from "./typecheck.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-typescript. DO NOT EDIT.";

const banner = (title: string, indent = "") => {
  const head = `${indent}// ── ${title} `;
  return head + "─".repeat(Math.max(3, 80 - head.length));
};

const shopSpec = `
  @service namespace Shop;
  model ErrorResponse { status: int32; code: string; message: string; correlationId?: string }
  namespace Graph {
    enum Kind { DATABASE, QUEUE }
    model Node { id: string; kind: Kind }
    model CreateNodeRequest { name: string }
    @route("/graph/nodes") interface Nodes {
      @get listNodes(@query kind?: Kind, @query offset?: int32, @query limit?: int32): Node[];
      @get readNode(@path id: string): Node;
      @post createNode(@body request: CreateNodeRequest): { @statusCode _: 201; @body node: Node };
      @delete deleteNode(@path id: string): void;
    }
  }
`;

const flat = { "client-style": "flat", "error-model": "ErrorResponse" };
const house = { layout: "single-file", errors: "thrown" };

const SHIPYARD_FLAGS = {
  exactOptionalPropertyTypes: true,
  noUncheckedIndexedAccess: true,
  noImplicitOverride: true,
  noFallthroughCasesInSwitch: true,
};

describe("flat client", () => {
  it("imports and re-exports the models from their own output dir", async () => {
    const { outputs } = await nextjs(
      { ...flat, "output-dir": "{emitter-output-dir}/web" },
      { ...house, "models-output-dir": "{emitter-output-dir}/shared" },
    ).compile(shopSpec);
    expect(outputs["web/client.ts"]).toContain(`from "../shared/types";`);
    expect(outputs["web/index.ts"]).toContain(`export * from "../shared/types";`);
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("emits one class with a method per operation and an ApiError from the error model", async () => {
    const { outputs } = await nextjs(flat, house).compile(shopSpec);
    expect(outputs["client.ts"]).toBe(`${HEADER}
import type { CreateNodeRequest, ErrorResponse, Kind, Node } from "./types";

export interface ClientOptions {
  baseUrl: string;
  /** Custom fetch implementation (defaults to the global fetch). */
  fetch?: typeof fetch;
  /** Headers sent with every request. */
  headers?: Record<string, string>;
}

/** Thrown for every non-2xx response. */
export class ApiError extends Error {
  readonly status: number;
  /** The decoded error body (ErrorResponse), when the response carried one. */
  readonly body: ErrorResponse | undefined;
  readonly code: string | undefined;
  readonly correlationId: string | undefined;

  constructor(status: number, body: ErrorResponse | undefined) {
    super(body?.message ?? \`Request failed with status \${status}\`);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
    this.code = body?.code;
    this.correlationId = body?.correlationId;
  }

  get isUnauthorized(): boolean {
    return this.status === 401;
  }

  get isForbidden(): boolean {
    return this.status === 403;
  }

  get isNotFound(): boolean {
    return this.status === 404;
  }

  get isConflict(): boolean {
    return this.status === 409;
  }
}

export class ShopClient {
  private readonly baseUrl: string;
  private readonly doFetch: typeof fetch;
  private readonly headers: Record<string, string>;

  constructor(options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\\/$/, "");
    this.doFetch = options.fetch ?? ((input, init) => globalThis.fetch(input, init));
    this.headers = options.headers ?? {};
  }

${banner("Nodes", "  ")}

  listNodes(query: { kind?: Kind; offset?: number; limit?: number } = {}): Promise<Node[]> {
    return this.send("GET", \`/graph/nodes\${toQuery(query)}\`);
  }

  readNode(id: string): Promise<Node> {
    return this.send("GET", \`/graph/nodes/\${encodeURIComponent(String(id))}\`);
  }

  createNode(request: CreateNodeRequest): Promise<Node> {
    return this.send("POST", "/graph/nodes", request);
  }

  async deleteNode(id: string): Promise<void> {
    await this.request("DELETE", \`/graph/nodes/\${encodeURIComponent(String(id))}\`);
  }

  private async send<T>(method: string, path: string, body?: unknown): Promise<T> {
    const response = await this.request(method, path, body);
    const text = await response.text();
    // An empty body (204 and the like) decodes to undefined.
    return (text ? JSON.parse(text) : undefined) as T;
  }

  private async request(method: string, path: string, body?: unknown): Promise<Response> {
    const headers = new globalThis.Headers(this.headers);
    if (body !== undefined) headers.set("content-type", "application/json");
    const response = await this.doFetch(\`\${this.baseUrl}\${path}\`, {
      method,
      headers,
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    if (!response.ok) throw await toError(response);
    return response;
  }
}

async function toError(response: Response): Promise<ApiError> {
  const body: unknown = await response.json().catch(() => undefined);
  return new ApiError(response.status, isErrorBody(body) ? body : undefined);
}

function isErrorBody(value: unknown): value is ErrorResponse {
  if (typeof value !== "object" || value === null) return false;
  const record = value as Record<string, unknown>;
  return ["status", "code", "message"].every((key) => record[key] !== undefined);
}

function toQuery(params: Record<string, unknown>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null) continue;
    for (const item of Array.isArray(value) ? value : [value]) search.append(key, String(item));
  }
  const rendered = search.toString();
  return rendered ? \`?\${rendered}\` : "";
}
`);
    expect(outputs["index.ts"]).toBe(`${HEADER}

export * from "./client";
export * from "./types";
`);
    expect(Object.keys(outputs).some((k) => k.startsWith("client/"))).toBe(false);
  });

  it("falls back to an untyped body without an error model", async () => {
    const { outputs } = await nextjs({ "client-style": "flat", "error-class": "HttpFailure" }, house).compile(shopSpec);
    const client = outputs["client.ts"];
    expect(client).toContain("export class HttpFailure extends Error {");
    expect(client).toContain("  readonly body: unknown;");
    expect(client).toContain("    super(`Request failed with status ${status}`);");
    expect(client).toContain("  return new HttpFailure(response.status, body);");
    expect(client).not.toContain("isErrorBody");
  });

  it("type-checks under shipyard's compiler flags, per-type and single-file", async () => {
    for (const emitterOptions of [house, {}]) {
      const { outputs } = await nextjs(flat, emitterOptions).compile(shopSpec);
      expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
    }
  });

  it("emits the private send() helper only in clients that have a non-void operation", async () => {
    const spec = `
      @service namespace Notifications {
        @route("/pings") interface Pings {
          @post ping(): void;
        }
      }
      @service namespace Orders {
        model Order { id: string }
        @route("/orders") interface OrdersOps {
          @get list(): Order[];
        }
      }
    `;
    const { outputs } = await nextjs({ "client-style": "flat" }, house).compile(spec);
    const client = outputs["client.ts"];
    expect(client).toContain("export class NotificationsClient {");
    expect(client).toContain("export class OrdersClient {");
    // Only OrdersClient's list() reads a body, so only it needs send(); NotificationsClient's
    // ping() is void and awaits request() directly.
    expect(client.match(/private async send<T>/g)?.length).toBe(1);
    expect(typecheck(outputs, { ...SHIPYARD_FLAGS, noUnusedLocals: true })).toBe("");
  });

  it("reports flat-style limitations instead of generating partial clients", async () => {
    const cases: [Record<string, unknown>, string, string][] = [
      [{ ...flat, "react-query": true }, shopSpec, "unsupported-in-flat-style"],
      [flat, `${shopSpec}\n@route("/other") interface Other { @get listNodes(): void; }`, "duplicate-operation-name"],
      [flat, shopSpec.replace("@get readNode(@path id: string): Node;", `@get readNode(@path id: string, @header trace: string): Node;`), "flat-client-unsupported"],
      [{ ...flat, "error-model": "Nope" }, shopSpec, "unknown-error-model"],
    ];
    for (const [options, spec, code] of cases) {
      const [, diagnostics] = await nextjs(options, house).compileAndDiagnose(spec);
      expectDiagnostics(diagnostics, { code: `@abhigyakrishna/tspgen-typescript/${code}` });
    }
  });

  it("reports generated types that clash with the flat client's exports", async () => {
    const cases: [Record<string, unknown>, string, string][] = [
      [flat, `${shopSpec}\nmodel ApiError { x: string }`, "ApiError"],
      [flat, `${shopSpec}\nmodel ClientOptions { x: string }`, "ClientOptions"],
      [flat, `${shopSpec}\nmodel ShopClient { x: string }`, "ShopClient"],
      // Even as the error model: index.ts re-exports both, so the name would be ambiguous.
      [{ "client-style": "flat", "error-model": "ApiError" }, `${shopSpec}\nmodel ApiError { message: string }`, "ApiError"],
    ];
    for (const [options, spec, name] of cases) {
      const [result, diagnostics] = await nextjs(options, house).compileAndDiagnose(spec);
      expectDiagnostics(diagnostics, {
        code: "@abhigyakrishna/tspgen-typescript/flat-client-name-clash",
        message: `Generated type '${name}' clashes with the flat client's own export; rename it with @TS.name or set error-class.`,
      });
      expect(result.outputs["client.ts"]).toBeUndefined();
    }
  });

  it("reports a generated type that shadows a global the flat client template uses", async () => {
    const spec = `${shopSpec}\nmodel Response { ok: boolean }\n@route("/thing") op thing(): Response;`;
    const [result, diagnostics] = await nextjs(flat, house).compileAndDiagnose(spec);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-typescript/flat-client-name-clash",
      message: "Generated type 'Response' clashes with a name the flat client uses internally ('Response'); rename it with @TS.name.",
    });
    expect(result.outputs["client.ts"]).toBeUndefined();
  });

  it("generates a JSON-only client alongside a model named Headers (request() uses globalThis.Headers)", async () => {
    const spec = `${shopSpec}\nmodel Headers { a: string }\n@route("/headers") op readHeaders(): Headers;`;
    const [result, diagnostics] = await nextjs(flat, house).compileAndDiagnose(spec);
    expect(diagnostics).toEqual([]);
    expect(result.outputs["client.ts"]).toContain("    const headers = new globalThis.Headers(this.headers);");
    expect(typecheck(result.outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("keeps nullable error-model fields nullable", async () => {
    const spec = shopSpec.replace("correlationId?: string }", "correlationId?: string; detail: string | null }");
    for (const emitterOptions of [house, {}]) {
      const { outputs } = await nextjs(flat, emitterOptions).compile(spec);
      expect(outputs["client.ts"]).toContain("  readonly detail: string | null | undefined;");
      expect(outputs["client.ts"]).toContain("    this.detail = body?.detail;");
      expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
    }
  });

  it("comma-joins array query values unless the parameter explodes", async () => {
    const spec = shopSpec.replace(
      "@get readNode(",
      `@get @route("/tagged") tagged(@query tags?: string[], @query(#{ explode: true }) labels?: string[], @query limit?: int32): Node[];
      @get readNode(`,
    );
    const { outputs } = await nextjs(flat, house).compile(spec);
    const client = outputs["client.ts"];
    expect(client).toContain(
      '  tagged(query: { tags?: string[]; labels?: string[]; limit?: number } = {}): Promise<Node[]> {\n    return this.send("GET", `/graph/nodes/tagged${toQuery(query, ["labels"])}`);',
    );
    expect(client).toContain('    return this.send("GET", `/graph/nodes${toQuery(query)}`);');
    expect(client).toContain("function toQuery(params: Record<string, unknown>, explode: readonly string[] = []): string {");
    expect(client).toContain('    else search.append(key, value.map(String).join(","));');
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");

    // The emitted toQuery, run as-is (its body is plain JavaScript once the signature is stripped).
    const body = client.slice(client.indexOf("function toQuery(")).replace(/^function toQuery\([^)]*\): string \{/, "").replace(/\}\n$/, "");
    const toQuery = new Function("params", "explode = []", body) as (p: Record<string, unknown>, e?: string[]) => string;
    expect(toQuery({ tags: ["a", "b"] })).toBe("?tags=a%2Cb");
    expect(decodeURIComponent(toQuery({ tags: ["a", "b"] }))).toBe("?tags=a,b");
    expect(toQuery({ tags: ["a", "b"] }, ["tags"])).toBe("?tags=a&tags=b");
    expect(toQuery({ limit: 5, skip: undefined })).toBe("?limit=5");
  });

  it("renames the query object when a path parameter or body is named query", async () => {
    const spec = `${shopSpec}
      model SearchRequest { text: string }
      @route("/search") interface Search {
        @post search(@body query: SearchRequest, @query limit?: int32): Graph.Node[];
      }`;
    const { outputs } = await nextjs(flat, house).compile(spec);
    expect(outputs["client.ts"]).toContain(
      '  search(query: SearchRequest, queryParams: { limit?: number } = {}): Promise<Node[]> {\n    return this.send("POST", `/search${toQuery(queryParams)}`, query);',
    );
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  const validatedSpec = "using TspGen;\n" + shopSpec
    .replace("model CreateNodeRequest { name: string }", "model CreateNodeRequest { @maxLength(64) name: string }")
    + `@@meta(Shop.Graph.CreateNodeRequest.name, "*", #{ notBlank: true });`;

  it("validates body and query with zod before fetch when validate is on", async () => {
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(validatedSpec);
    const client = outputs["client.ts"];
    expect(client).toContain(`import { z } from "zod";`);
    expect(client).toContain(`import { CreateNodeRequestSchema, KindSchema } from "./types";`);
    expect(client).toContain(
      `  async listNodes(query: { kind?: Kind; offset?: number; limit?: number } = {}): Promise<Node[]> {\n` +
        `    z.object({ kind: z.lazy(() => KindSchema).optional(), offset: z.number().int().optional(), limit: z.number().int().optional() }).parse(query);\n`,
    );
    expect(client).toContain(
      `  async createNode(request: CreateNodeRequest): Promise<Node> {\n    z.lazy(() => CreateNodeRequestSchema).parse(withoutUndefined(request));\n`,
    );
    // path params without constraints are not re-checked
    expect(client).toContain(`  readNode(id: string): Promise<Node> {\n    return this.send(`);
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("makes checked methods async so validation errors reject", async () => {
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(validatedSpec);
    expect(outputs["client.ts"]).toContain(`  async createNode(request: CreateNodeRequest): Promise<Node> {\n`);
    // no checks: stays a plain method returning the promise
    expect(outputs["client.ts"]).toContain(`  readNode(id: string): Promise<Node> {\n`);
  });

  it("checks constrained path parameters, constrained bodies and optional bodies", async () => {
    const spec = `${validatedSpec}
      @route("/v") interface V {
        @get @route("/codes/{id}") readCode(@path @minLength(3) id: string): Graph.Node;
        @post @route("/tags") tag(@body @maxItems(2) items: string[]): void;
        @put @route("/nodes/{id}") upsert(@path id: string, @body body?: Graph.CreateNodeRequest): Graph.Node;
      }`;
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(spec);
    const client = outputs["client.ts"];
    expect(client).toContain(`  async readCode(id: string): Promise<Node> {\n    z.string().min(3).parse(id);\n    return this.send(`);
    expect(client).toContain(`  async tag(items: string[]): Promise<void> {\n    z.array(z.string()).max(2).parse(withoutUndefined(items));\n`);
    expect(client).toContain(
      `  async upsert(id: string, body?: CreateNodeRequest): Promise<Node> {\n` +
        `    if (body !== undefined) z.lazy(() => CreateNodeRequestSchema).parse(withoutUndefined(body));\n    return this.send(`,
    );
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("checks a @bodyRoot array body against its constraints", async () => {
    const spec = `${validatedSpec}
      @route("/labels") op label(@bodyRoot @maxItems(2) items: string[]): void;`;
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(spec);
    expect(outputs["client.ts"]).toContain(`  async label(items: string[]): Promise<void> {\n    z.array(z.string()).max(2).parse(withoutUndefined(items));\n`);
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
  });

  it("validates bodies without their undefined-valued keys, emitting the helper only when used", async () => {
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(validatedSpec);
    expect(outputs["client.ts"]).toContain(`

/** A copy without \`undefined\`-valued keys (as JSON would send it), for validation only. */
function withoutUndefined(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(withoutUndefined);
  if (value === null || typeof value !== "object") return value;
  const proto: unknown = Object.getPrototypeOf(value);
  if (proto !== Object.prototype && proto !== null) return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([, entry]) => entry !== undefined)
      .map(([key, entry]) => [key, withoutUndefined(entry)]),
  );
}
`);
    expect(typecheck(outputs, { ...SHIPYARD_FLAGS, noUnusedLocals: true })).toBe("");
    // only query checks: no body to strip
    const queryOnly = `using TspGen;
      @service namespace Q;
      @route("/q") op find(@query @maxValue(5) limit?: int32): void;`;
    const plain = await nextjs({ "client-style": "flat", validate: true }, { ...house, zod: true }).compile(queryOnly);
    expect(plain.outputs["client.ts"]).toContain(".parse(query);");
    expect(plain.outputs["client.ts"]).not.toContain("withoutUndefined");
    expect((await nextjs(flat, { ...house, zod: true }).compile(validatedSpec)).outputs["client.ts"]).not.toContain("withoutUndefined");
  });

  it("renames method identifiers named z so they do not shadow the zod import", async () => {
    const spec = `${validatedSpec}
      model Tile { data: string }
      model Z { v: string }
      @route("/tiles") interface Tiles {
        @get @route("/{z}/{x}/{y}") tile(@path z: int32, @path x: int32, @path y: int32, @query format?: string): Tile;
        @post @route("/{zValue}") put(@path zValue: string, @body z: Z): void;
      }`;
    const { outputs } = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).compile(spec);
    const client = outputs["client.ts"];
    expect(client).not.toContain("z: number");
    expect(client).toContain(
      "  async tile(zValue: number, x: number, y: number, query: { format?: string } = {}): Promise<Tile> {\n",
    );
    expect(client).toContain("`/tiles/${encodeURIComponent(String(zValue))}/");
    expect(client).toContain("  async put(zValue: string, zValue2: Z): Promise<void> {\n    z.lazy(() => ZSchema).parse(withoutUndefined(zValue2));\n");
    expect(client).toContain(", zValue2);\n");
    expect(typecheck(outputs, SHIPYARD_FLAGS)).toBe("");
    // without validate there is no zod import to shadow
    const plain = (await nextjs(flat, { ...house, zod: true }).compile(spec)).outputs["client.ts"];
    expect(plain).toContain("  tile(z: number, x: number, y: number,");
  });

  it("reports a generated type named z when validate is on", async () => {
    const spec = `${validatedSpec}
      @TS.name("z") model Zed { v: string }
      @route("/zed") op zed(): Zed;`;
    const diagnostics = await nextjs({ ...flat, validate: true }, { ...house, zod: true }).diagnose(spec);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-typescript/flat-client-name-clash",
      message: "Generated type 'z' clashes with a name the flat client uses internally ('z'); rename it with @TS.name.",
    });
  });

  it("emits no validation without the validate option", async () => {
    const { outputs } = await nextjs(flat, { ...house, zod: true }).compile(validatedSpec);
    // Matches the validation check calls (z.object(...).parse(...) / z.lazy(...).parse(...)) without
    // false-positiving on the unrelated `JSON.parse(text)` in the client's private send() helper.
    expect(outputs["client.ts"]).not.toMatch(/z\.(object|lazy)\(/);
    expect(outputs["client.ts"]).not.toContain(`from "zod"`);
  });

  it("requires zod for validate", async () => {
    const diagnostics = await nextjs({ ...flat, validate: true }, house).diagnose(validatedSpec);
    expectDiagnostics(diagnostics, { code: "@abhigyakrishna/tspgen-typescript/validate-requires-zod" });
  });

  it("reports operations the flat client cannot express", async () => {
    const cases: [string, string][] = [
      [`@route("/text") op text(): { @header contentType: "text/plain"; @body body: string };`, "a non-JSON response"],
      [`@route("/send") op send(): void;`, "its name clashes with a client member"],
      [`@route("/headers") op headers(): void;`, "its name clashes with a client member"],
      [`@route("/opt/{id}") op opt(@path id?: string): void;`, "optional path parameters"],
    ];
    for (const [op, reason] of cases) {
      const [result, diagnostics] = await nextjs(flat, house).compileAndDiagnose(`${shopSpec}\n${op}`);
      expectDiagnostics(diagnostics, { code: "@abhigyakrishna/tspgen-typescript/flat-client-unsupported", message: new RegExp(`: ${reason}\\.$`) });
      expect(result.outputs["client.ts"]).toBeUndefined();
    }
  });
});
