import { resolvePath } from "@typespec/compiler";
import { createTester } from "@typespec/compiler/testing";
import { resolve } from "node:path";

export const Tester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@specgen/emitter-kotlin"],
})
  .importLibraries()
  .using("Http");

export const TARGET = resolve(import.meta.dirname, "../dist/index.js");

export function server(targetOptions: Record<string, unknown> = {}, emitterOptions: Record<string, unknown> = {}) {
  return Tester.emit("@specgen/emitter-kotlin", {
    package: "com.acme",
    targets: [{ [TARGET]: targetOptions }],
    ...emitterOptions,
  });
}

export const HEADER = "// Code generated by @specgen/emitter-kotlin. DO NOT EDIT.";

export const petSpec = `
  @service namespace PetStore;
  model Pet { id: int64; name: string }
  @error model ApiError { code: string }
  @route("/pets") interface Pets {
    @get list(@query limit?: int32, @query(#{ explode: true }) tags?: string[]): Pet[];
    @get get(@path petId: int64, @header("x-trace") trace?: string): Pet | ApiError;
    @post create(@body pet: Pet): { @statusCode _: 201; @header location: string; @body pet: Pet } | { @statusCode _: 200; @body pet: Pet };
    @delete remove(@path petId: int64): void;
  }
`;
