import { resolvePath } from "@typespec/compiler";
import { createTester } from "@typespec/compiler/testing";
import { resolve } from "node:path";

export const Tester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@tspgen/emitter-core", "@tspgen/emitter-kotlin"],
})
  .importLibraries()
  .using("Http");

export const TARGET = resolve(import.meta.dirname, "../dist/index.js");

export function client(targetOptions: Record<string, unknown> = {}) {
  return Tester.emit("@tspgen/emitter-kotlin", { package: "com.acme", targets: [{ [TARGET]: targetOptions }] });
}

export const HEADER = "// Code generated by @tspgen/emitter-kotlin. DO NOT EDIT.";
