import { resolvePath } from "@typespec/compiler";
import { createTester } from "@typespec/compiler/testing";
import { resolve } from "node:path";

export const Tester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@abhigyakrishna/tspgen-core", "@abhigyakrishna/tspgen-kotlin"],
})
  .importLibraries()
  .using("Http");

export const TARGET = resolve(import.meta.dirname, "../dist/index.js");

export function client(targetOptions: Record<string, unknown> = {}, emitterOptions: Record<string, unknown> = {}) {
  return Tester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme", targets: [{ [TARGET]: targetOptions }], ...emitterOptions });
}

export const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

/** Tester with the optional SSE libraries (`@typespec/streams`, `@typespec/events`, `@typespec/sse`). */
export const SseTester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: [
    "@typespec/http",
    "@typespec/streams",
    "@typespec/events",
    "@typespec/sse",
    "@abhigyakrishna/tspgen-core",
    "@abhigyakrishna/tspgen-kotlin",
  ],
})
  .importLibraries()
  .using("Http", "SSE", "Events");

export function sseClient(targetOptions: Record<string, unknown> = {}) {
  return SseTester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme", targets: [{ [TARGET]: targetOptions }] });
}
