emit:
  - "@abhigyakrishna/tspgen-typescript"
options:
  "@abhigyakrishna/tspgen-typescript":
    emitter-output-dir: "{project-root}/generated/v2"
    # no version: the latest (v2)
    features:
      zod: true
    targets:
      - "@abhigyakrishna/tspgen-ts-nextjs-client": {}
