emit:
  - "@tspgen/emitter-kotlin"
options:
  "@tspgen/emitter-kotlin":
    emitter-output-dir: "{project-root}/build/generated/tspgen"
    package: "com.example.petstore"
    targets:
      - "@tspgen/kotlin-ktor-server": {}
      - "@tspgen/kotlin-ktor-client": {}
