emit:
  - "@abhigyakrishna/tspgen-kotlin"
options:
  "@abhigyakrishna/tspgen-kotlin":
    emitter-output-dir: "{project-root}/build/generated/tspgen-resources"
    package: "com.example.secure.resources"
    targets:
      - "@abhigyakrishna/tspgen-kotlin-ktor-server":
          routing-style: resources
          auth-providers:
            PartnerKey: com.example.petstore.PARTNER_PROVIDER
          sse-headers:
            Cache-Control: no-cache
            X-Stream: secure
