import { coreEmitterOptionsSchemaProperties, type LanguageEmitterOptions } from "@abhigyakrishna/tspgen-core";
import { createTypeSpecLibrary, paramMessage, type JSONSchemaType } from "@typespec/compiler";

export interface TypeScriptEmitterOptions extends LanguageEmitterOptions {
  zod?: boolean;
  "import-extension"?: "none" | ".js";
  layout?: "per-type" | "single-file";
  errors?: "typed" | "thrown";
}

const optionsSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    ...coreEmitterOptionsSchemaProperties,
    zod: { type: "boolean", nullable: true, description: "Emit zod schemas next to the types (default false)." },
    "import-extension": {
      type: "string",
      enum: ["none", ".js"],
      nullable: true,
      description: 'Suffix for relative imports: "none" for bundlers/Next.js (default), ".js" for Node ESM.',
    },
    layout: {
      type: "string",
      enum: ["per-type", "single-file"],
      nullable: true,
      description: "per-type (default): models/<Name>.ts + barrel; single-file: every model in types.ts.",
    },
    errors: {
      type: "string",
      enum: ["typed", "thrown"],
      nullable: true,
      description: "typed (default): <Body>Error classes; thrown: error responses are documentation only.",
    },
    targets: {
      type: "array",
      nullable: true,
      items: {
        anyOf: [
          { type: "string" },
          { type: "object", minProperties: 1, maxProperties: 1, additionalProperties: { type: "object" } },
        ],
      },
    },
  },
  required: [],
} as const;

export const $lib = createTypeSpecLibrary({
  name: "@abhigyakrishna/tspgen-typescript",
  diagnostics: {
    "duplicate-operation-name": {
      severity: "error",
      messages: {
        default: paramMessage`Operations '${"first"}' and '${"second"}' are both named '${"name"}' in the flat client; rename one (e.g. @TS.name).`,
      },
    },
    "unsupported-in-flat-style": {
      severity: "error",
      messages: {
        default: paramMessage`Option '${"option"}' is not supported with client-style "flat".`,
      },
    },
    "flat-client-unsupported": {
      severity: "error",
      messages: {
        default: paramMessage`Operation '${"operation"}' cannot be generated by the flat client: ${"reason"}.`,
      },
    },
    "auth-header-conflict": {
      severity: "warning",
      messages: {
        default: paramMessage`Operation '${"operation"}' sends several credentials (${"schemes"}) as the '${"header"}' header in one auth alternative; ${"target"} sends only the last one.`,
      },
    },
    "unknown-error-model": {
      severity: "error",
      messages: {
        default: paramMessage`error-model '${"name"}' does not name a generated model.`,
      },
    },
    "flat-client-name-clash": {
      severity: "error",
      messages: {
        default: paramMessage`Generated type '${"name"}' clashes with the flat client's own export; rename it with @TS.name or set error-class.`,
        local: paramMessage`Generated type '${"name"}' clashes with a name the flat client uses internally ('${"name"}'); rename it with @TS.name.`,
      },
    },
    "non-json-body": {
      severity: "warning",
      messages: {
        default: paramMessage`Operation '${"operation"}' has a non-JSON body (${"contentType"}); only a client method is generated for it.`,
      },
    },
    "duplicate-type-name": {
      severity: "error",
      messages: {
        default: paramMessage`TypeScript type '${"name"}' is generated from both '${"first"}' and '${"second"}'. Use @TS.name to disambiguate.`,
      },
    },
    "invalid-pattern": {
      severity: "warning",
      messages: {
        default: paramMessage`@pattern '${"pattern"}' on '${"where"}' is not a valid JavaScript regular expression; it is not validated.`,
      },
    },
    "validate-requires-zod": {
      severity: "error",
      messages: {
        default: "Option 'validate' needs zod schemas; set zod: true on @abhigyakrishna/tspgen-typescript.",
      },
    },
    "validate-flat-only": {
      severity: "warning",
      messages: {
        default:
          "Option 'validate' only applies to client-style \"flat\"; the grouped client validates responses and Server Action input already.",
      },
    },
  },
  emitter: { options: optionsSchema as unknown as JSONSchemaType<TypeScriptEmitterOptions> },
});

export const { reportDiagnostic } = $lib;
