import {
  coreEmitterOptionsSchemaProperties,
  coreFeatures,
  defaultHeaderText,
  defineFeatures,
  movedOptionSchemas,
  type LanguageEmitterOptions,
  type MovedOptions,
} from "@abhigyakrishna/tspgen-core";
import { createTypeSpecLibrary, paramMessage, type JSONSchemaType } from "@typespec/compiler";

export interface TypeScriptEmitterOptions extends LanguageEmitterOptions {
  /** Moved to `features.zod` in 0.2.0. */
  zod?: unknown;
  "import-extension"?: "none" | ".js";
  layout?: "per-type" | "single-file";
  errors?: "typed" | "thrown";
}

export const TYPESCRIPT_EMITTER = "@abhigyakrishna/tspgen-typescript";

export const typescriptFeatures = defineFeatures({
  ...coreFeatures,
  zod: {
    default: false,
    description: "zod schemas (<Name>Schema) next to the types, constraint decorators as refinements; needs zod >= 4.3.",
  },
  barrel: { default: true, description: "models/index.ts re-exporting every model (per-type layout)." },
});

/** TypeScript emitter option keys moved in 0.2.0. */
export const typescriptMovedOptions: MovedOptions = { zod: "features.zod" };

const optionsSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    ...coreEmitterOptionsSchemaProperties,
    "header-text": {
      ...coreEmitterOptionsSchemaProperties["header-text"],
      default: defaultHeaderText(TYPESCRIPT_EMITTER),
    },
    features: typescriptFeatures.openSchema,
    "import-extension": {
      type: "string",
      enum: ["none", ".js"],
      nullable: true,
      default: "none",
      description: 'Suffix for relative imports: "none" for bundlers/Next.js (default), ".js" for Node ESM.',
    },
    layout: {
      type: "string",
      enum: ["per-type", "single-file"],
      nullable: true,
      default: "per-type",
      description: "per-type (default): models/<Name>.ts + barrel; single-file: every model in types.ts.",
    },
    errors: {
      type: "string",
      enum: ["typed", "thrown"],
      nullable: true,
      default: "typed",
      description: "typed (default): <Body>Error classes; thrown: error responses are documentation only.",
    },
    ...movedOptionSchemas(typescriptMovedOptions),
    targets: {
      type: "array",
      nullable: true,
      items: {
        anyOf: [
          { type: "string" },
          { type: "object", minProperties: 1, maxProperties: 1, additionalProperties: { type: "object" } },
        ],
      },
    },
  },
  required: [],
} as const;

export const $lib = createTypeSpecLibrary({
  name: "@abhigyakrishna/tspgen-typescript",
  diagnostics: {
    "api-version-name-clash": {
      severity: "error",
      messages: {
        default: paramMessage`Generated type '${"name"}' (${"id"}) has the name of the version constant '${"name"}'; rename it with @TS.name. The constant is not generated.`,
      },
    },
    "duplicate-operation-name": {
      severity: "error",
      messages: {
        default: paramMessage`Operations '${"first"}' and '${"second"}' are both named '${"name"}' in the flat client; rename one (e.g. @TS.name).`,
      },
    },
    "flat-client-unsupported": {
      severity: "error",
      messages: {
        default: paramMessage`Operation '${"operation"}' cannot be generated by the flat client: ${"reason"}.`,
      },
    },
    "auth-header-conflict": {
      severity: "warning",
      messages: {
        default: paramMessage`Operation '${"operation"}' sends several credentials (${"schemes"}) as the '${"header"}' header in one auth alternative; ${"target"} sends only the last one.`,
      },
    },
    "unknown-error-model": {
      severity: "error",
      messages: {
        default: paramMessage`error-model '${"name"}' does not name a generated model.`,
      },
    },
    "flat-client-name-clash": {
      severity: "error",
      messages: {
        default: paramMessage`Generated type '${"name"}' clashes with the flat client's own export; rename it with @TS.name or set error-class.`,
        local: paramMessage`Generated type '${"name"}' clashes with a name the flat client uses internally ('${"name"}'); rename it with @TS.name.`,
      },
    },
    "flat-react-query-name-clash": {
      severity: "error",
      messages: {
        default: paramMessage`'${"first"}' and '${"second"}' both generate '${"name"}' in the flat client's React Query code; rename one (e.g. @TS.name).`,
      },
    },
    "flat-react-query-skipped": {
      severity: "warning",
      messages: {
        default: paramMessage`Operation '${"operation"}' gets no React Query hooks, keys or Vars: ${"reason"}.`,
      },
    },
    "non-json-body": {
      severity: "warning",
      messages: {
        default: paramMessage`Operation '${"operation"}' has a non-JSON body (${"contentType"}); only a client method is generated for it.`,
      },
    },
    "duplicate-type-name": {
      severity: "error",
      messages: {
        default: paramMessage`TypeScript type '${"name"}' is generated from both '${"first"}' and '${"second"}'. Use @TS.name to disambiguate.`,
      },
    },
    "sse-message-conflict": {
      severity: "error",
      messages: {
        default: paramMessage`Type '${"id"}' is generated as SseMessage, the type untyped server-sent events use; rename it with @TS.name.`,
      },
    },
    "invalid-pattern": {
      severity: "warning",
      messages: {
        default: paramMessage`@pattern '${"pattern"}' on '${"where"}' is not a valid JavaScript regular expression; it is not validated.`,
      },
    },
  },
  emitter: { options: optionsSchema as unknown as JSONSchemaType<TypeScriptEmitterOptions> },
});

export const { reportDiagnostic } = $lib;
