import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { emitter } from "./tester.js";

function dirWith(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "tspgen-kt-"));
  for (const [path, content] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, path)), { recursive: true });
    writeFileSync(join(dir, path), content);
  }
  return dir;
}

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

const petSpec = `
  @service namespace PetStore;
  /** A pet */
  model Pet {
    id: int64;
    name?: string;
    tags: string[];
    @encodedName("application/json", "born_at") bornAt: utcDateTime;
    color: Color = Color.red;
    weight?: float64 = 1.5;
  }
  enum Color { red, darkBlue: "dark-blue" }
  @discriminator("kind") model Animal { kind: string; name: string }
  model Dog extends Animal { kind: "dog"; bark: boolean }
  model Empty {}
`;

describe("@abhigyakrishna/tspgen-kotlin models", () => {
  it("emits data classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toBe(`${HEADER}
@file:UseSerializers(InstantSerializer::class)
package com.acme.models

import java.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

/**
 * A pet
 */
@Serializable
data class Pet(
    val id: Long,
    val name: String? = null,
    val tags: List<String>,
    @SerialName("born_at")
    val bornAt: Instant,
    val color: Color = Color.RED,
    val weight: Double = 1.5,
)
`);
  });

  it("maps date/time scalars to java.time with generated ISO-8601 serializers", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Slot { at: utcDateTime; day: plainDate; times: plainTime[]; length?: duration; zoned: offsetDateTime }
      model Plain { name: string }
    `);
    expect(outputs["models/com/acme/models/Slot.kt"]).toBe(`${HEADER}
@file:UseSerializers(InstantSerializer::class, OffsetDateTimeSerializer::class, LocalDateSerializer::class, LocalTimeSerializer::class, DurationSerializer::class)
package com.acme.models

import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.time.OffsetDateTime
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

@Serializable
data class Slot(
    val at: Instant,
    val day: LocalDate,
    val times: List<LocalTime>,
    val length: Duration? = null,
    val zoned: OffsetDateTime,
)
`);
    expect(outputs["models/com/acme/models/Plain.kt"]).not.toContain("UseSerializers");
    const serializers = outputs["models/com/acme/models/JavaTimeSerializers.kt"];
    expect(serializers).toContain(`object InstantSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("java.time.Instant", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())

    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}`);
    expect(serializers).toContain("object DurationSerializer : KSerializer<Duration> {");
  });

  it("writes java.time types qualified when a generated type has the same name", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Duration { minutes: int32 }
      model W { d: duration; x: Duration }
    `);
    const w = outputs["models/com/acme/models/W.kt"];
    expect(w).toContain("    val d: java.time.Duration,\n    val x: Duration,\n");
    expect(w).not.toContain("import java.time.Duration");
    expect(w).toContain("@file:UseSerializers(DurationSerializer::class)");
    expect(outputs["models/com/acme/models/JavaTimeSerializers.kt"]).toContain("object DurationSerializer");
  });

  it("keeps kotlin.time and kotlinx.datetime with date-time: kotlin.time", async () => {
    const { outputs } = await emitter({ "date-time": "kotlin.time" }).compile(`
      @service namespace S;
      model Slot { at: utcDateTime; day: plainDate; length: duration }
    `);
    const slot = outputs["models/com/acme/models/Slot.kt"];
    expect(slot).toContain("import kotlin.time.Duration\nimport kotlin.time.Instant\nimport kotlinx.datetime.LocalDate\n");
    expect(slot).not.toContain("UseSerializers");
    expect(outputs["models/com/acme/models/JavaTimeSerializers.kt"]).toBeUndefined();
  });

  it("emits no serializers when no model uses java.time", async () => {
    const { outputs } = await emitter().compile(`@service namespace S; model Plain { name: string }`);
    expect(outputs["models/com/acme/models/JavaTimeSerializers.kt"]).toBeUndefined();
  });

  it("nests variants only a sealed union uses inside it, named after their keys", async () => {
    const { outputs } = await emitter({ validation: true }).compile(`
      using TspGen;
      @service namespace S;
      model Cat { @minLength(1) name: string; at: utcDateTime; @Kotlin.type("java.util.UUID") id: string }
      model Dog { name: string }
      model Shared { name: string }
      @Kotlin.name("Hound") model Wolf { name: string }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Pet { cat: Cat, dog: Dog, shared: Shared, wolf: Wolf }
      model UsesShared { s: Shared }
      model Owner { pet: Pet }
    `);
    expect(outputs["models/com/acme/models/Pet.kt"]).toBe(`${HEADER}
@file:UseSerializers(InstantSerializer::class)
package com.acme.models

import java.time.Instant
import java.util.UUID
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers
import kotlinx.serialization.json.JsonClassDiscriminator

@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("kind")
sealed interface Pet {
    @Serializable
    @SerialName("cat")
    data class Cat(
        val name: String,
        val at: Instant,
        val id: UUID,
    ) : Pet {
        init {
            require(name.isNotEmpty()) { "name must not be empty" }
        }
    }

    @Serializable
    @SerialName("dog")
    data class Dog(
        val name: String,
    ) : Pet

    @Serializable
    @SerialName("wolf")
    data class Hound(
        val name: String,
    ) : Pet
}
`);
    // Shared is also used by UsesShared, so it stays top-level.
    expect(outputs["models/com/acme/models/Shared.kt"]).toContain("data class Shared(\n    val name: String,\n) : Pet");
    for (const gone of ["Cat", "Dog", "Wolf", "Hound"]) expect(outputs[`models/com/acme/models/${gone}.kt`]).toBeUndefined();
  });

  it("nests single-use variants from other namespaces too, in the union's package", async () => {
    const { outputs } = await emitter({
      packages: [{ namespace: "S.Other", package: "com.acme.other" }],
    }).compile(`
      @service namespace S;
      model Catalog { id: string }
      namespace Other { model Remote { id: string } }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "type" })
      union Source { catalog: Catalog, remote: Other.Remote }
      @route("/sources") op read(): Source;
    `);
    const source = outputs["models/com/acme/models/Source.kt"];
    expect(source).toContain("    data class Catalog(\n        val id: String,\n    ) : Source");
    expect(source).toContain("    data class Remote(");
    expect(outputs["models/com/acme/other/Remote.kt"]).toBeUndefined();
  });

  it("does not give a nested variant a name its union or siblings refer to", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Catalog { id: string }
      model CatalogSource { catalog: Catalog }
      model UrlSource { url: string }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Source { catalog: CatalogSource, url: UrlSource }
      model ShapeA { x: int32 }
      model Other { y: int32 }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Shape { shape: ShapeA, other: Other }
    `);
    const source = outputs["models/com/acme/models/Source.kt"];
    expect(source).toContain("    data class CatalogSource(\n        val catalog: Catalog,\n    ) : Source");
    expect(source).toContain("    data class Url(");
    const shape = outputs["models/com/acme/models/Shape.kt"];
    expect(shape).toContain("    data class ShapeA(");
    expect(shape).toContain("    data class Other(");
  });

  it("keeps a variant top-level when nesting would move it away from its sealed base's package", async () => {
    const { outputs } = await emitter({ packages: [{ namespace: "S.Base", package: "com.acme.base" }] }).compile(`
      @service namespace S;
      namespace Base {
        @discriminator("type") model Animal { type: string }
        model Cat extends Animal { type: "cat"; lives: int32 }
      }
      model Other { y: int32 }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Pick { cat: Base.Cat, other: Other }
    `);
    expect(outputs["models/com/acme/base/Cat.kt"]).toContain("data class Cat(");
    expect(outputs["models/com/acme/models/Pick.kt"]).toContain("    data class Other(");
  });

  it("keeps every variant top-level with union-variants: top-level", async () => {
    const { outputs } = await emitter({ "union-variants": "top-level" }).compile(`
      @service namespace S;
      model Cat { name: string }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Pet { cat: Cat }
    `);
    expect(outputs["models/com/acme/models/Cat.kt"]).toContain("data class Cat(");
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain("sealed interface Pet\n");
  });

  it("emits template models once as generic data classes", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Page<T> { items: T[]; total: int64 }
      model Pair<K, V> { key: K; value: V }
      model Pet { id: int64 }
      model Holder { pets: Page<Pet>; names: Page<string>; pair: Pair<string, Page<Pet>> }
      @route("/pets") op list(): Page<Pet>;
    `);
    expect(outputs["models/com/acme/models/Page.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.Serializable

@Serializable
data class Page<T>(
    val items: List<T>,
    val total: Long,
)
`);
    expect(outputs["models/com/acme/models/Holder.kt"]).toContain(`    val pets: Page<Pet>,
    val names: Page<String>,
    val pair: Pair<String, Page<Pet>>,`);
    expect(Object.keys(outputs).some((p) => p.includes("PagePet"))).toBe(false);
  });

  it("maps generic templates with @Kotlin.type to the mapped class with arguments", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      @Kotlin.type("com.acme.core.Page") model Page<T> { items: T[] }
      model Pet { id: int64 }
      model Holder { pets: Page<Pet> }
    `);
    const holder = outputs["models/com/acme/models/Holder.kt"];
    expect(holder).toContain("import com.acme.core.Page\n");
    expect(holder).toContain("    val pets: Page<Pet>,");
    expect(outputs["models/com/acme/models/Page.kt"]).toBeUndefined();
  });

  it("emits one model per template instance with generics: false", async () => {
    const { outputs } = await emitter({ generics: false }).compile(`
      @service namespace S;
      model Page<T> { items: T[] }
      model Pet { id: int64 }
      model Holder { pets: Page<Pet> }
    `);
    expect(outputs["models/com/acme/models/PagePet.kt"]).toContain("data class PagePet(\n    val items: List<Pet>,\n)");
  });

  it("emits enums", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Color.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Color {
    @SerialName("red")
    RED,
    @SerialName("dark-blue")
    DARK_BLUE,
}
`);
  });

  it("omits @SerialName on enum members whose value is their Kotlin name", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      enum Mode { READ, WRITE: "write" }
      enum Plain { A, B }
    `);
    expect(outputs["models/com/acme/models/Mode.kt"]).toContain(`enum class Mode {
    READ,
    @SerialName("write")
    WRITE,
}`);
    const plain = outputs["models/com/acme/models/Plain.kt"];
    expect(plain).not.toContain("SerialName");
    expect(plain).toContain(`enum class Plain {
    A,
    B,
}`);
  });

  it("emits sealed hierarchies and empty classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Animal.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("kind")
sealed interface Animal {
    val name: String
}
`);
    expect(outputs["models/com/acme/models/Dog.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dog")
data class Dog(
    override val name: String,
    val bark: Boolean,
) : Animal
`);
    expect(outputs["models/com/acme/models/Empty.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.Serializable

@Serializable
class Empty
`);
  });

  it("emits typealiases and honours @Kotlin.packageName imports", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      union Loose { "a", string }
      @Kotlin.packageName("com.acme.other") model Other { x: int32 }
      model UsesOther { other: Other }
    `);
    expect(outputs["models/com/acme/models/Loose.kt"]).toBe(`${HEADER}
package com.acme.models

typealias Loose = String
`);
    expect(outputs["models/com/acme/other/Other.kt"]).toContain("package com.acme.other");
    expect(outputs["models/com/acme/models/UsesOther.kt"]).toContain("import com.acme.other.Other\n");
  });

  it("uses template overrides from template-dir", async () => {
    const templateDir = dirWith({ "kotlin/common/header.eta": "// custom header" });
    const { outputs } = await emitter({ "template-dir": templateDir }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"].startsWith("// custom header\n@file:UseSerializers(InstantSerializer::class)\npackage com.acme.models")).toBe(true);
  });

  it("applies plugins", async () => {
    const dir = dirWith({
      "plugin.mjs": `export default {
        name: "audit",
        transformIR(ir) {
          for (const d of ir.declarations) if (d.kind === "data-class") d.annotations.push("@Audited");
        },
      };`,
    });
    const { outputs } = await emitter({ plugins: [join(dir, "plugin.mjs")] }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain("@Audited\n@Serializable\ndata class Pet(");
  });

  it("loads external targets with their templates and options", async () => {
    const dir = dirWith({
      "templates/demo/summary.eta": "<%= it.count %> declarations, style=<%= it.style %>",
      "target.mjs": `
        import { fileURLToPath } from "node:url";
        export default {
          name: "demo", kind: "server", language: "kotlin",
          templates: fileURLToPath(new URL("./templates", import.meta.url)),
          optionsSchema: { type: "object", properties: { style: { type: "string", default: "dsl" } } },
          files: (ir, ctx) => [{ path: "server/summary.txt", template: "demo/summary",
            data: { count: ir.declarations.length, style: ctx.options.style } }],
        };`,
    });
    const { outputs } = await emitter({ targets: [join(dir, "target.mjs")] }).compile(petSpec);
    expect(outputs["server/summary.txt"]).toBe("5 declarations, style=dsl\n");
  });
});
