import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { emitter } from "./tester.js";

function dirWith(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "tspgen-kt-"));
  for (const [path, content] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, path)), { recursive: true });
    writeFileSync(join(dir, path), content);
  }
  return dir;
}

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

const petSpec = `
  @service namespace PetStore;
  /** A pet */
  model Pet {
    id: int64;
    name?: string;
    tags: string[];
    @encodedName("application/json", "born_at") bornAt: utcDateTime;
    color: Color = Color.red;
    weight?: float64 = 1.5;
  }
  enum Color { red, darkBlue: "dark-blue" }
  @discriminator("kind") model Animal { kind: string; name: string }
  model Dog extends Animal { kind: "dog"; bark: boolean }
  model Empty {}
`;

describe("@abhigyakrishna/tspgen-kotlin models", () => {
  it("emits data classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toBe(`${HEADER}
@file:UseSerializers(InstantSerializer::class)
package com.acme.models

import java.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

/**
 * A pet
 */
@Serializable
data class Pet(
    val id: Long,
    val name: String? = null,
    val tags: List<String>,
    @SerialName("born_at")
    val bornAt: Instant,
    val color: Color = Color.RED,
    val weight: Double = 1.5,
)
`);
  });

  it("maps date/time scalars to java.time with generated ISO-8601 serializers", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Slot { at: utcDateTime; day: plainDate; times: plainTime[]; length?: duration; zoned: offsetDateTime }
      model Plain { name: string }
    `);
    expect(outputs["models/com/acme/models/Slot.kt"]).toBe(`${HEADER}
@file:UseSerializers(InstantSerializer::class, OffsetDateTimeSerializer::class, LocalDateSerializer::class, LocalTimeSerializer::class, DurationSerializer::class)
package com.acme.models

import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalTime
import java.time.OffsetDateTime
import kotlinx.serialization.Serializable
import kotlinx.serialization.UseSerializers

@Serializable
data class Slot(
    val at: Instant,
    val day: LocalDate,
    val times: List<LocalTime>,
    val length: Duration? = null,
    val zoned: OffsetDateTime,
)
`);
    expect(outputs["models/com/acme/models/Plain.kt"]).not.toContain("UseSerializers");
    const serializers = outputs["models/com/acme/models/JavaTimeSerializers.kt"];
    expect(serializers).toContain(`object InstantSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("java.time.Instant", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Instant) = encoder.encodeString(value.toString())

    override fun deserialize(decoder: Decoder): Instant = Instant.parse(decoder.decodeString())
}`);
    expect(serializers).toContain("object DurationSerializer : KSerializer<Duration> {");
  });

  it("keeps kotlin.time and kotlinx.datetime with date-time: kotlin.time", async () => {
    const { outputs } = await emitter({ "date-time": "kotlin.time" }).compile(`
      @service namespace S;
      model Slot { at: utcDateTime; day: plainDate; length: duration }
    `);
    const slot = outputs["models/com/acme/models/Slot.kt"];
    expect(slot).toContain("import kotlin.time.Duration\nimport kotlin.time.Instant\nimport kotlinx.datetime.LocalDate\n");
    expect(slot).not.toContain("UseSerializers");
    expect(outputs["models/com/acme/models/JavaTimeSerializers.kt"]).toBeUndefined();
  });

  it("emits no serializers when no model uses java.time", async () => {
    const { outputs } = await emitter().compile(`@service namespace S; model Plain { name: string }`);
    expect(outputs["models/com/acme/models/JavaTimeSerializers.kt"]).toBeUndefined();
  });

  it("emits enums", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Color.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Color {
    @SerialName("red")
    RED,
    @SerialName("dark-blue")
    DARK_BLUE,
}
`);
  });

  it("omits @SerialName on enum members whose value is their Kotlin name", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      enum Mode { READ, WRITE: "write" }
      enum Plain { A, B }
    `);
    expect(outputs["models/com/acme/models/Mode.kt"]).toContain(`enum class Mode {
    READ,
    @SerialName("write")
    WRITE,
}`);
    const plain = outputs["models/com/acme/models/Plain.kt"];
    expect(plain).not.toContain("SerialName");
    expect(plain).toContain(`enum class Plain {
    A,
    B,
}`);
  });

  it("emits sealed hierarchies and empty classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Animal.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("kind")
sealed interface Animal {
    val name: String
}
`);
    expect(outputs["models/com/acme/models/Dog.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dog")
data class Dog(
    override val name: String,
    val bark: Boolean,
) : Animal
`);
    expect(outputs["models/com/acme/models/Empty.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.Serializable

@Serializable
class Empty
`);
  });

  it("emits typealiases and honours @Kotlin.packageName imports", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      union Loose { "a", string }
      @Kotlin.packageName("com.acme.other") model Other { x: int32 }
      model UsesOther { other: Other }
    `);
    expect(outputs["models/com/acme/models/Loose.kt"]).toBe(`${HEADER}
package com.acme.models

typealias Loose = String
`);
    expect(outputs["models/com/acme/other/Other.kt"]).toContain("package com.acme.other");
    expect(outputs["models/com/acme/models/UsesOther.kt"]).toContain("import com.acme.other.Other\n");
  });

  it("uses template overrides from template-dir", async () => {
    const templateDir = dirWith({ "kotlin/common/header.eta": "// custom header" });
    const { outputs } = await emitter({ "template-dir": templateDir }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"].startsWith("// custom header\n@file:UseSerializers(InstantSerializer::class)\npackage com.acme.models")).toBe(true);
  });

  it("applies plugins", async () => {
    const dir = dirWith({
      "plugin.mjs": `export default {
        name: "audit",
        transformIR(ir) {
          for (const d of ir.declarations) if (d.kind === "data-class") d.annotations.push("@Audited");
        },
      };`,
    });
    const { outputs } = await emitter({ plugins: [join(dir, "plugin.mjs")] }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain("@Audited\n@Serializable\ndata class Pet(");
  });

  it("loads external targets with their templates and options", async () => {
    const dir = dirWith({
      "templates/demo/summary.eta": "<%= it.count %> declarations, style=<%= it.style %>",
      "target.mjs": `
        import { fileURLToPath } from "node:url";
        export default {
          name: "demo", kind: "server", language: "kotlin",
          templates: fileURLToPath(new URL("./templates", import.meta.url)),
          optionsSchema: { type: "object", properties: { style: { type: "string", default: "dsl" } } },
          files: (ir, ctx) => [{ path: "server/summary.txt", template: "demo/summary",
            data: { count: ir.declarations.length, style: ctx.options.style } }],
        };`,
    });
    const { outputs } = await emitter({ targets: [join(dir, "target.mjs")] }).compile(petSpec);
    expect(outputs["server/summary.txt"]).toBe("5 declarations, style=dsl\n");
  });
});
