import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { emitter } from "./tester.js";

function dirWith(files: Record<string, string>): string {
  const dir = mkdtempSync(join(tmpdir(), "tspgen-kt-"));
  for (const [path, content] of Object.entries(files)) {
    mkdirSync(dirname(join(dir, path)), { recursive: true });
    writeFileSync(join(dir, path), content);
  }
  return dir;
}

const HEADER = "// Code generated by @tspgen/emitter-kotlin. DO NOT EDIT.";

const petSpec = `
  @service namespace PetStore;
  /** A pet */
  model Pet {
    id: int64;
    name?: string;
    tags: string[];
    @encodedName("application/json", "born_at") bornAt: utcDateTime;
    color: Color = Color.red;
    weight?: float64 = 1.5;
  }
  enum Color { red, darkBlue: "dark-blue" }
  @discriminator("kind") model Animal { kind: string; name: string }
  model Dog extends Animal { kind: "dog"; bark: boolean }
  model Empty {}
`;

describe("@tspgen/emitter-kotlin models", () => {
  it("emits data classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlin.time.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A pet
 */
@Serializable
data class Pet(
    val id: Long,
    val name: String? = null,
    val tags: List<String>,
    @SerialName("born_at")
    val bornAt: Instant,
    val color: Color = Color.RED,
    val weight: Double = 1.5,
)
`);
  });

  it("emits enums", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Color.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Color {
    @SerialName("red")
    RED,
    @SerialName("dark-blue")
    DARK_BLUE,
}
`);
  });

  it("emits sealed hierarchies and empty classes", async () => {
    const { outputs } = await emitter().compile(petSpec);
    expect(outputs["models/com/acme/models/Animal.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("kind")
sealed interface Animal {
    val name: String
}
`);
    expect(outputs["models/com/acme/models/Dog.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dog")
data class Dog(
    override val name: String,
    val bark: Boolean,
) : Animal
`);
    expect(outputs["models/com/acme/models/Empty.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.Serializable

@Serializable
class Empty
`);
  });

  it("emits typealiases and honours @Kotlin.packageName imports", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      union Loose { "a", string }
      @Kotlin.packageName("com.acme.other") model Other { x: int32 }
      model UsesOther { other: Other }
    `);
    expect(outputs["models/com/acme/models/Loose.kt"]).toBe(`${HEADER}
package com.acme.models

typealias Loose = String
`);
    expect(outputs["models/com/acme/other/Other.kt"]).toContain("package com.acme.other");
    expect(outputs["models/com/acme/models/UsesOther.kt"]).toContain("import com.acme.other.Other\n");
  });

  it("uses template overrides from template-dir", async () => {
    const templateDir = dirWith({ "kotlin/common/header.eta": "// custom header" });
    const { outputs } = await emitter({ "template-dir": templateDir }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"].startsWith("// custom header\npackage com.acme.models")).toBe(true);
  });

  it("applies plugins", async () => {
    const dir = dirWith({
      "plugin.mjs": `export default {
        name: "audit",
        transformIR(ir) {
          for (const d of ir.declarations) if (d.kind === "data-class") d.annotations.push("@Audited");
        },
      };`,
    });
    const { outputs } = await emitter({ plugins: [join(dir, "plugin.mjs")] }).compile(petSpec);
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain("@Audited\n@Serializable\ndata class Pet(");
  });

  it("loads external targets with their templates and options", async () => {
    const dir = dirWith({
      "templates/demo/summary.eta": "<%= it.count %> declarations, style=<%= it.style %>",
      "target.mjs": `
        import { fileURLToPath } from "node:url";
        export default {
          name: "demo", kind: "server", language: "kotlin",
          templates: fileURLToPath(new URL("./templates", import.meta.url)),
          optionsSchema: { type: "object", properties: { style: { type: "string", default: "dsl" } } },
          files: (ir, ctx) => [{ path: "server/summary.txt", template: "demo/summary",
            data: { count: ir.declarations.length, style: ctx.options.style } }],
        };`,
    });
    const { outputs } = await emitter({ targets: [join(dir, "target.mjs")] }).compile(petSpec);
    expect(outputs["server/summary.txt"]).toBe("5 declarations, style=dsl\n");
  });
});
