import { resolvePath } from "@typespec/compiler";
import { createTester, expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { emitter } from "./tester.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";
const PET = "models/com/acme/models/Pet.kt";
const OWNER = "models/com/acme/models/Owner.kt";

const docSpec = `
  using TspGen;
  @service namespace S;
  /** A pet */
  model Pet { /** Its name */ name: string }
  /** An owner */
  @meta("kotlin", #{ features: #{ docs: false } })
  model Owner { /** Owner name */ name: string }
`;

describe("kotlin: header", () => {
  it("renders the default header", async () => {
    const { outputs } = await emitter().compile(docSpec);
    expect(outputs[PET].startsWith(`${HEADER}\npackage com.acme.models\n`)).toBe(true);
  });

  it("renders no header with features.header false", async () => {
    const { outputs } = await emitter({ features: { header: false } }).compile(docSpec);
    expect(outputs[PET].startsWith("package com.acme.models\n")).toBe(true);
  });

  it("renders a custom single-line and multi-line header-text as line comments", async () => {
    const single = await emitter({ "header-text": "Owned by the platform team" }).compile(docSpec);
    expect(single.outputs[PET].startsWith("// Owned by the platform team\npackage com.acme.models\n")).toBe(true);
    const multi = await emitter({ "header-text": "@generated\n\nDo not edit." }).compile(docSpec);
    expect(multi.outputs[PET].startsWith("// @generated\n//\n// Do not edit.\npackage com.acme.models\n")).toBe(true);
  });

  it("treats header-text: \"\" as unset, rendering the default banner", async () => {
    const { outputs } = await emitter({ "header-text": "" }).compile(docSpec);
    expect(outputs[PET].startsWith(`${HEADER}\npackage com.acme.models\n`)).toBe(true);
  });
});

describe("kotlin: docs", () => {
  it("renders KDoc by default and none for a declaration with features.docs false", async () => {
    const { outputs } = await emitter().compile(docSpec);
    expect(outputs[PET]).toContain("/**\n * A pet\n */\n");
    expect(outputs[PET]).toContain("    /**\n     * Its name\n     */\n");
    expect(outputs[OWNER]).not.toContain("An owner");
    expect(outputs[OWNER]).not.toContain("Owner name");
  });

  it("renders no KDoc with features.docs false, except where @meta turns it back on", async () => {
    const { outputs } = await emitter({ features: { docs: false } }).compile(`
      using TspGen;
      @service namespace S;
      /** A pet */ model Pet { name: string }
      /** Kept */ @meta("kotlin", #{ features: #{ docs: true } }) model Kept { name: string }
    `);
    expect(outputs[PET]).not.toContain("A pet");
    expect(outputs["models/com/acme/models/Kept.kt"]).toContain("/**\n * Kept\n */\n");
  });

  it("inherits features.docs from the namespace", async () => {
    const { outputs } = await emitter().compile(`
      using TspGen;
      @meta("kotlin", #{ features: #{ docs: false } })
      @service namespace S;
      /** A pet */ model Pet { name: string }
    `);
    expect(outputs[PET]).not.toContain("A pet");
  });
});

describe("kotlin: generics", () => {
  it("emits one model per instance for a template with features.generics false", async () => {
    const { outputs } = await emitter().compile(`
      using TspGen;
      @service namespace S;
      @meta("kotlin", #{ features: #{ generics: false } }) model Page<T> { items: T[] }
      model Box<T> { item: T }
      model Pet { id: int64 }
      model Holder { pets: Page<Pet>; box: Box<Pet> }
    `);
    expect(outputs["models/com/acme/models/PagePet.kt"]).toContain("data class PagePet(\n    val items: List<Pet>,\n)");
    expect(outputs["models/com/acme/models/Page.kt"]).toBeUndefined();
    expect(outputs["models/com/acme/models/Box.kt"]).toContain("data class Box<T>(");
  });

  it("rejects the moved generics option", async () => {
    const diagnostics = await emitter({ generics: false }).diagnose(`@service namespace S; model Pet { id: int64 }`);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-core/option-moved",
      message: "`generics` moved to `features.generics` in 0.2.0.",
    });
  });
});

describe("kotlin: validation", () => {
  const constrained = `@service namespace S; model Req { @maxLength(200) name: string }`;
  const REQ = "models/com/acme/models/Req.kt";

  it("renders constraint checks by default", async () => {
    const { outputs } = await emitter().compile(constrained);
    expect(outputs[REQ]).toContain(`        if (!(name.length <= 200)) throw ModelCheckException("name must be at most 200 characters")\n`);
  });

  it("renders no checks with features.validation false", async () => {
    const { outputs } = await emitter({ features: { validation: false } }).compile(constrained);
    expect(outputs[REQ]).not.toContain("init {");
  });

  it("rejects the moved validation option", async () => {
    const diagnostics = await emitter({ validation: true }).diagnose(constrained);
    expectDiagnostics(diagnostics, {
      code: "@abhigyakrishna/tspgen-core/option-moved",
      message: "`validation` moved to `features.validation` in 0.2.0.",
    });
  });
});

describe("kotlin: visibility", () => {
  const spec = `
    @service namespace S;
    model Pet { id: int64; at: utcDateTime }
    enum Color { red }
    model Circle { r: int32 }
    @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
    union Shape { circle: Circle }
    @error model Oops { code: string }
    @route("/p") op get(): Pet | Oops;
  `;

  it("renders no modifier by default", async () => {
    const { outputs } = await emitter().compile(spec);
    expect(outputs[PET]).toContain("\ndata class Pet(");
    expect(Object.values(outputs).some((c) => c.includes("internal "))).toBe(false);
  });

  it("marks every top-level declaration internal, nested ones not", async () => {
    const { outputs } = await emitter({ visibility: "internal" }).compile(spec);
    expect(outputs[PET]).toContain("\ninternal data class Pet(");
    expect(outputs["models/com/acme/models/Color.kt"]).toContain("\ninternal enum class Color {");
    const shape = outputs["models/com/acme/models/Shape.kt"];
    expect(shape).toContain("\ninternal sealed interface Shape");
    expect(shape).toContain("\n    data class Circle(");
    expect(shape).not.toContain("internal data class Circle");
    const time = outputs["models/com/acme/models/ModelSerializers.kt"];
    expect(time).toContain("\ninternal object InstantSerializer : KSerializer<Instant> {");
    expect(time).toContain("\ninternal val modelSerializersModule: SerializersModule");
    expect(outputs["models/com/acme/api/ApiException.kt"]).toContain("\ninternal open class ApiException(");
    expect(outputs["models/com/acme/api/OopsException.kt"]).toContain("\ninternal class OopsException(");
  });

  const WideTester = createTester(resolvePath(import.meta.dirname, ".."), {
    libraries: [
      "@typespec/http",
      "@typespec/versioning",
      "@typespec/streams",
      "@typespec/events",
      "@typespec/sse",
      "@abhigyakrishna/tspgen-core",
      "@abhigyakrishna/tspgen-kotlin",
    ],
  })
    .importLibraries()
    .using("Http", "Versioning", "SSE", "Events");

  function wide(options: Record<string, unknown> = {}) {
    return WideTester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme", ...options });
  }

  const wideSpec = `
    @service @versioned(Versions) namespace S;
    enum Versions { v1: "2024-01-01", v2: "2024-06-01" }
    model Pet { id: int64; name: string }
    union Loose { "a", string }
    @events union ChannelEvents { note: Pet }
    @route("/ops") interface Ops {
      @route("/c") subscribe(): SSEStream<ChannelEvents>;
      @post create(@body pet: Pet): { @statusCode _: 201; @header location: string; @body pet: Pet } | { @statusCode _: 200; @body pet: Pet };
      @post @route("raw") raw(@bodyRoot file: File<"image/png">): void;
    }
  `;

  it("marks internal every top-level declaration across a versioned service, a typealias, a result, SSE events and HttpFile, nested ones not", async () => {
    const { outputs } = await wide({ visibility: "internal" }).compile(wideSpec);
    expect(outputs["models/com/acme/models/ApiVersionConstants.kt"]).toContain('\ninternal const val API_VERSION: String = "2024-06-01"');
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain("\ninternal data class Pet(");
    expect(outputs["models/com/acme/models/Loose.kt"]).toContain("\ninternal typealias Loose = String");
    const events = outputs["models/com/acme/models/ChannelEvents.kt"];
    expect(events).toContain("\ninternal sealed interface ChannelEvents {");
    expect(events).toContain("\n    data class Note(");
    expect(events).not.toContain("internal data class Note");
    const result = outputs["models/com/acme/api/CreateResult.kt"];
    expect(result).toContain("\ninternal sealed interface CreateResult {");
    expect(result).toContain("\n    data class Created(");
    expect(result).toContain("\n    data class Ok(");
    expect(result).not.toContain("internal data class Created");
    expect(result).not.toContain("internal data class Ok");
    expect(outputs["models/com/acme/models/HttpFile.kt"]).toContain("\ninternal class HttpFile(");
  });
});

describe("kotlin: file-annotations", () => {
  it("adds @file: annotations after UseSerializers", async () => {
    const { outputs } = await emitter({ "file-annotations": ['Suppress("unused")'] }).compile(`
      @service namespace S;
      model Pet { at: utcDateTime }
      enum Color { red }
    `);
    expect(outputs[PET].startsWith(`${HEADER}\n@file:UseSerializers(InstantSerializer::class)\n@file:Suppress("unused")\npackage com.acme.models\n`)).toBe(true);
    expect(outputs["models/com/acme/models/Color.kt"].startsWith(`${HEADER}\n@file:Suppress("unused")\npackage com.acme.models\n`)).toBe(true);
  });

  it("strips a leading @file: so both forms render the same annotation once", async () => {
    const bare = await emitter({ "file-annotations": ['Suppress("unused")'] }).compile(`
      @service namespace S;
      enum Color { red }
    `);
    const prefixed = await emitter({ "file-annotations": ['@file:Suppress("unused")'] }).compile(`
      @service namespace S;
      enum Color { red }
    `);
    const COLOR = "models/com/acme/models/Color.kt";
    expect(bare.outputs[COLOR].startsWith(`${HEADER}\n@file:Suppress("unused")\npackage com.acme.models\n`)).toBe(true);
    expect(prefixed.outputs[COLOR].startsWith(`${HEADER}\n@file:Suppress("unused")\npackage com.acme.models\n`)).toBe(true);
  });

  it("trims a leading-space entry before stripping @file:", async () => {
    const { outputs } = await emitter({ "file-annotations": [' @file:Suppress("unused")'] }).compile(`
      @service namespace S;
      enum Color { red }
    `);
    const COLOR = "models/com/acme/models/Color.kt";
    expect(outputs[COLOR].startsWith(`${HEADER}\n@file:Suppress("unused")\npackage com.acme.models\n`)).toBe(true);
  });
});
