import { buildApiIR } from "@abhigyakrishna/tspgen-core";
import { describe, expect, it } from "vitest";
import { transformToKotlin, type KotlinIR, type KotlinTransformOptions, type KtDecl } from "../src/transform/index.js";
import { emitter, Tester } from "./tester.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

async function transform(code: string, options: Partial<KotlinTransformOptions> = {}) {
  const [{ program }, diagnostics] = await Tester.compileAndDiagnose(code);
  const ir = transformToKotlin(program, buildApiIR(program), {
    package: "com.acme",
    enumMemberNaming: "UPPER_SNAKE",
    ...options,
  });
  return { program, ir, diagnostics };
}

function decl(ir: KotlinIR, name: string): KtDecl {
  const found = ir.declarations.find((d) => d.name === name);
  if (!found) throw new Error(`no declaration ${name}: ${ir.declarations.map((d) => d.name).join(", ")}`);
  return found;
}

describe("kotlin house-style options", () => {
  it("maps namespaces to packages, longest prefix wins", async () => {
    const { ir } = await transform(
      `
      @service namespace S;
      model Shared { id: string }
      namespace Graph {
        model Node { id: string }
        namespace Deep { model Leaf { id: string } }
      }
      namespace Other { model Thing { id: string } }
      namespace Pinned { @Kotlin.packageName("com.pinned") model Kept { id: string } }
    `,
      { packages: { S: "com.acme.shared", "S.Graph": "com.acme.graph" } },
    );
    expect(decl(ir, "Shared").package).toBe("com.acme.shared");
    expect(decl(ir, "Node").package).toBe("com.acme.graph");
    expect(decl(ir, "Leaf").package).toBe("com.acme.graph");
    expect(decl(ir, "Thing").package).toBe("com.acme.shared");
    expect(decl(ir, "Kept").package).toBe("com.pinned");
  });

  it("ignores prototype keys when mapping namespaces to packages", async () => {
    const { ir } = await transform(
      `
      namespace constructor { model Ctor { id: string } }
      namespace toString { model Str { id: string } }
      @service namespace S { model Holder { c: constructor.Ctor; s: toString.Str } }
    `,
      { packages: { Other: "com.other" } },
    );
    expect(decl(ir, "Ctor").package).toBe("com.acme.models");
    expect(decl(ir, "Str").package).toBe("com.acme.models");
  });

  it("gives groups their mapped package and inherits namespace metadata into operations", async () => {
    const { ir } = await transform(
      `
      using TspGen;
      @meta("kotlin", #{ annotations: #["@Root"] })
      @service namespace S;
      @meta("kotlin", #{ annotations: #["@Graph"] })
      namespace Graph {
        @meta("kotlin", #{ annotations: #["@Iface"] })
        @route("/nodes") interface Nodes { @get list(): void; }
      }
    `,
      { packages: { "S.Graph": "com.acme.graph" } },
    );
    const group = ir.services[0].groups[0];
    expect(group.package).toBe("com.acme.graph");
    expect(group.operations[0].annotations).toEqual(["@Root", "@Graph", "@Iface"]);
  });

  it("deduplicates annotations inherited from several metadata levels", async () => {
    const { ir } = await transform(`
      using TspGen;
      @meta("kotlin", #{ annotations: #["@Iface"] })
      @service namespace S;
      @meta("kotlin", #{ annotations: #["@Iface", "@Own"] })
      @route("/nodes") interface Nodes { @get list(): void; }
    `);
    const group = ir.services[0].groups[0];
    expect(group.annotations).toEqual(["@Iface", "@Own"]);
    expect(group.operations[0].annotations).toEqual(["@Iface", "@Own"]);
  });

  it("accepts the new emitter options", async () => {
    const { outputs } = await emitter({ packages: [{ namespace: "S.Graph", package: "com.acme.graph" }], errors: "thrown", features: { validation: true } }).compile(`
      @service namespace S;
      namespace Graph { model Node { id: string } }
    `);
    expect(outputs["models/com/acme/graph/Node.kt"]).toContain("package com.acme.graph\n");
  });

  it("rejects a record-shaped packages option (tspconfig keys cannot contain dots)", async () => {
    const [, diagnostics] = await emitter({ packages: { "S.Graph": "com.acme.graph" } }).compileAndDiagnose(`
      @service namespace S;
    `);
    expect(diagnostics.map((d) => d.code)).toContain("invalid-schema");
  });

  it("errors: thrown drops typed exceptions but keeps success results and ApiException", async () => {
    const spec = `
      @service namespace S;
      model Pet { id: string }
      @error model NotFound { @statusCode _: 404; message: string }
      @route("/pets") interface Pets {
        @get read(@path id: string): Pet | NotFound;
        @post create(@body pet: Pet): { @statusCode _: 201; @body pet: Pet } | { @statusCode _: 200; @body pet: Pet } | NotFound;
      }
    `;
    const { ir } = await transform(spec, { errors: "thrown" });
    const [read, create] = ir.services[0].groups[0].operations;
    expect(read.errors).toEqual([]);
    expect(read.result).toMatchObject({ kind: "single", status: 200, type: { text: "Pet" } });
    expect(create.errors).toEqual([]);
    expect(create.result.kind).toBe("sealed");
    expect(ir.apiDeclarations.map((d) => d.name)).toEqual(["ApiException", "CreateResult"]);

    const typed = await transform(spec);
    expect(typed.ir.apiDeclarations.map((d) => d.name)).toEqual(["ApiException", "NotFoundException", "CreateResult"]);
  });

  it("keys typed exceptions by error model FQN and disambiguates clashing names", async () => {
    const { ir } = await transform(
      `
      @service namespace Shop;
      namespace A {
        @error model Err { @statusCode _: 404; m: string }
        @route("/a") interface As { @get read(): void | Err; }
      }
      namespace B {
        @error model Err { @statusCode _: 404; m: string }
        @route("/b") interface Bs { @get read(): void | Err; }
      }
    `,
      { packages: { "Shop.A": "com.x.a", "Shop.B": "com.x.b" } },
    );
    const exceptions = ir.apiDeclarations.filter((d) => d.kind === "exception");
    expect(exceptions.map((d) => d.name)).toEqual(["ErrException", "BErrException"]);
    const bodies = exceptions.map((d) => (d.kind === "exception" ? d.body.imports : []));
    expect(bodies).toEqual([["com.x.a.Err"], ["com.x.b.Err"]]);
    const [a, b] = ir.services[0].groups.map((g) => g.operations[0]);
    expect(a.errors.map((e) => e.exception.text)).toEqual(["ErrException"]);
    expect(b.errors.map((e) => e.exception.text)).toEqual(["BErrException"]);
  });

  it("renders templated external models with mapped arguments and maps custom scalars", async () => {
    const { ir } = await transform(`
      @service namespace S;
      model Page<T> { items: T[]; total: int64 }
      scalar isoInstant extends utcDateTime;
      model Node { id: string; createdAt: isoInstant }
      model Holder { page: Page<Node>; nested: Page<Page<Node>> }
      @@Kotlin.type(S.Page, "com.acme.core.Page");
      @@Kotlin.type(S.isoInstant, "com.acme.core.IsoInstant");
    `);
    const node = decl(ir, "Node");
    if (node.kind !== "data-class") throw new Error("expected data class");
    expect(node.properties[1].type).toEqual({ text: "IsoInstant", imports: ["com.acme.core.IsoInstant"], nullable: false });
    const holder = decl(ir, "Holder");
    if (holder.kind !== "data-class") throw new Error("expected data class");
    expect(holder.properties.map((p) => p.type.text)).toEqual(["Page<Node>", "Page<Page<Node>>"]);
    expect(new Set(holder.properties[1].type.imports)).toEqual(new Set(["com.acme.core.Page", "com.acme.models.Node"]));
    expect(ir.declarations.map((d) => d.name).filter((n) => n.startsWith("Page"))).toEqual([]);
  });

  it("features.validation renders constraint checks in init; @meta checks lines are appended", async () => {
    const { outputs } = await emitter({ features: { validation: true } }).compile(`
      using TspGen;
      @service namespace S;
      @meta("kotlin", #{ checks: #["require((a == null) == (b == null)) { \\"a and b go together\\" }"] })
      model Req {
        @minLength(1) @maxLength(200) name: string;
        @minLength(3) code?: string;
        @pattern("^[a-z]+$") slug: string;
        @minItems(1) @maxItems(10) tags: string[];
        @minValue(0) @maxValue(100) score: int32;
        a?: string;
        b?: string;
      }
    `);
    expect(outputs["models/com/acme/models/Req.kt"]).toBe(`${HEADER}
package com.acme.models

import kotlinx.serialization.Serializable

@Serializable
data class Req(
    val name: String,
    val code: String? = null,
    val slug: String,
    val tags: List<String>,
    val score: Int,
    val a: String? = null,
    val b: String? = null,
) {
    init {
        require(name.isNotEmpty()) { "name must not be empty" }
        require(name.length <= 200) { "name must be at most 200 characters" }
        require(code == null || code.length >= 3) { "code must be at least 3 characters" }
        require(Regex("^[a-z]+\\$").containsMatchIn(slug)) { "slug must match ^[a-z]+\\$" }
        require(tags.size >= 1) { "tags must have at least 1 item" }
        require(tags.size <= 10) { "tags must have at most 10 items" }
        require(score >= 0) { "score must be at least 0" }
        require(score <= 100) { "score must be at most 100" }
        require((a == null) == (b == null)) { "a and b go together" }
    }
}
`);
  });

  it("notBlank meta renders isNotBlank(), with or without validation, and subsumes @minLength(1)", async () => {
    const spec = `
      using TspGen;
      @service namespace S;
      model Req {
        @meta("*", #{ notBlank: true }) @minLength(1) name: string;
        @meta("kotlin", #{ notBlank: true }) note?: string;
      }
    `;
    const checks = [
      `require(name.isNotBlank()) { "name must not be blank" }`,
      `require(note == null || note.isNotBlank()) { "note must not be blank" }`,
    ];
    for (const validation of [true, false]) {
      const req = (await emitter({ features: { validation } }).compile(spec)).outputs["models/com/acme/models/Req.kt"];
      for (const check of checks) expect(req).toContain(check);
      expect(req).not.toContain("isNotEmpty()");
    }
  });

  it("renders @pattern as an unanchored containsMatchIn check", async () => {
    const { outputs } = await emitter({ features: { validation: true } }).compile(`
      @service namespace S;
      model Req { @pattern("[0-9]") code: string }
    `);
    const req = outputs["models/com/acme/models/Req.kt"];
    expect(req).toContain(`require(Regex("[0-9]").containsMatchIn(code)) { "code must match [0-9]" }`);
    expect(req).not.toContain(".matches(");
  });

  it("checks scalar-level constraints of a nullable custom scalar", async () => {
    const { outputs } = await emitter({ features: { validation: true } }).compile(`
      @service namespace S;
      scalar Slug extends string;
      @@pattern(Slug, "^[a-z]+$");
      model Req { b: Slug | null }
    `);
    expect(outputs["models/com/acme/models/Req.kt"]).toContain(
      `require(b == null || Regex("^[a-z]+\\$").containsMatchIn(b)) { "b must match ^[a-z]+\\$" }`,
    );
  });

  it("renders no checks with features.validation false", async () => {
    const { outputs } = await emitter({ features: { validation: false } }).compile(`
      @service namespace S;
      model Req { @maxLength(200) name: string }
    `);
    expect(outputs["models/com/acme/models/Req.kt"]).not.toContain("init {");
  });

  it("skips validation checks for properties removed by discriminated unions", async () => {
    // TypeSpec's discriminated-union-none validation requires an explicitly-declared
    // discriminator property to have a string-literal type matching the variant name, which is
    // incompatible with @pattern (which requires a plain `string` scalar). So the constrained
    // property is declared under its own name and wired to the discriminator via @encodedName:
    // TypeSpec's own discriminant check looks up the property by its TypeSpec name ("kind", not
    // found, so it's skipped), while our IR's `fillUnion` matches by wire name ("kind") and
    // removes it from the variant's properties — exactly the case under test.
    const { outputs } = await emitter({ features: { validation: true } }).compile(`
      using TspGen;
      @service namespace S;
      model Cat {
        @encodedName("application/json", "kind") @pattern("^cat$") realKind: string;
        name: string;
      }
      model Dog {
        @encodedName("application/json", "kind") altKind: string;
        name: string;
      }
      @discriminated(#{ envelope: "none", discriminatorPropertyName: "kind" })
      union Pet { cat: Cat, dog: Dog }
    `);
    const pet = outputs["models/com/acme/models/Pet.kt"];
    expect(pet).toContain("data class Cat(");
    expect(pet).not.toContain("containsMatchIn(");
  });

  it("renders defaults for empty collections, empty models and mapped enums", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      enum Kind { A, B }
      model Vec2 { x?: float64 = 0; y?: float64 = 0 }
      model Holder {
        tags?: string[] = #[];
        attrs?: Record<string> = #{};
        position?: Vec2 = #{};
        kind?: Kind = Kind.B;
      }
      @@Kotlin.type(S.Kind, "com.acme.core.Kind");
    `);
    const holder = outputs["models/com/acme/models/Holder.kt"];
    expect(holder).toContain("    val tags: List<String> = emptyList(),\n");
    expect(holder).toContain("    val attrs: Map<String, String> = emptyMap(),\n");
    expect(holder).toContain("    val position: Vec2 = Vec2(),\n");
    expect(holder).toContain("    val kind: Kind = Kind.B,\n");
    expect(holder).toContain("import com.acme.core.Kind\n");
  });
});
