import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { buildApiIR } from "@abhigyakrishna/tspgen-core";
import { transformToKotlin } from "../src/transform/index.js";
import { emitter, Tester } from "./tester.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";
const M = "models/com/acme/models";
const EXCEPTION = `${M}/ModelCheckException.kt`;

describe("ModelCheckException", () => {
  it("is emitted when a model has a generated check, which throws it", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Req { @maxLength(5) name: string }
    `);
    expect(outputs[EXCEPTION]).toBe(`${HEADER}
package com.acme.models

/**
 * Thrown by the models' generated checks (constraint decorators, \`notBlank\`) when a value violates one; the message
 * names the property and the rule, e.g. "name must not be blank". An [IllegalArgumentException], as \`require\` throws.
 */
class ModelCheckException(message: String) : IllegalArgumentException(message)
`);
    const req = outputs[`${M}/Req.kt`];
    expect(req).toContain(`        if (!(name.length <= 5)) throw ModelCheckException("name must be at most 5 characters")\n`);
    expect(req).not.toContain("require(");
    expect(req).not.toContain("import com.acme.models.ModelCheckException");
  });

  it("is not emitted without checks", async () => {
    const spec = `
      @service namespace S;
      model Req { @maxLength(5) name: string }
    `;
    const { outputs } = await emitter({ features: { validation: false } }).compile(spec);
    expect(outputs[EXCEPTION]).toBeUndefined();
    for (const [path, text] of Object.entries(outputs)) expect(text, path).not.toContain("ModelCheckException");
  });

  it("follows visibility: internal", async () => {
    const { outputs } = await emitter({ visibility: "internal" }).compile(`
      @service namespace S;
      model Req { @minItems(1) tags: string[] }
    `);
    expect(outputs[EXCEPTION]).toContain("\ninternal class ModelCheckException(message: String) : IllegalArgumentException(message)\n");
  });

  it("is thrown by value-class scalar checks", async () => {
    const { outputs } = await emitter({ "scalar-style": "value-class" }).compile(`
      @service namespace S;
      @minLength(3) scalar PetId extends string;
      model Pet { id: PetId }
    `);
    expect(outputs[`${M}/PetId.kt`]).toContain(
      `        if (!(value.length >= 3)) throw ModelCheckException("PetId must be at least 3 characters")\n`,
    );
    expect(outputs[EXCEPTION]).toBeDefined();
  });

  it("is imported by models in other packages", async () => {
    const { outputs } = await emitter({ packages: [{ namespace: "S.Other", package: "com.acme.other" }] }).compile(`
      @service namespace S;
      namespace Other { model Remote { @minValue(1) n: int32 } }
      model Holder { remote: Other.Remote }
    `);
    const remote = outputs["models/com/acme/other/Remote.kt"];
    expect(remote).toContain("import com.acme.models.ModelCheckException\n");
    expect(remote).toContain(`if (!(n >= 1)) throw ModelCheckException("n must be at least 1")`);
    expect(outputs[EXCEPTION]).toBeDefined();
  });

  it("is emitted for @meta checks that throw it, and not for other @meta checks", async () => {
    const meta = (line: string) => `
      using TspGen;
      @service namespace S;
      @meta("kotlin", #{ checks: #["${line}"] })
      model Req { a?: string; b?: string }
    `;
    const throwing = (await emitter().compile(meta('if ((a == null) != (b == null)) throw ModelCheckException(\\"a and b go together\\")'))).outputs;
    expect(throwing[EXCEPTION]).toBeDefined();
    const requiring = (await emitter().compile(meta('require((a == null) == (b == null)) { \\"a and b go together\\" }'))).outputs;
    expect(requiring[EXCEPTION]).toBeUndefined();
  });

  it("reports a model generated as ModelCheckException when checks need it", async () => {
    const [, diagnostics] = await emitter().compileAndDiagnose(`
      @service namespace S;
      model ModelCheckException { @minLength(1) reason: string }
    `);
    expectDiagnostics(diagnostics.filter((d) => d.code.endsWith("model-check-exception-conflict")), {
      code: "@abhigyakrishna/tspgen-kotlin/model-check-exception-conflict",
      message: /Model 'S.ModelCheckException' is generated as 'com.acme.models.ModelCheckException'/,
    });
  });

  it("exposes its FQN on the IR only when emitted", async () => {
    const ir = async (spec: string) => {
      const { program } = await Tester.compile(spec);
      return transformToKotlin(program, buildApiIR(program), { package: "com.acme", enumMemberNaming: "UPPER_SNAKE", validation: true });
    };
    expect((await ir(`@service namespace S; model Req { @maxLength(5) name: string }`)).modelCheckException).toBe(
      "com.acme.models.ModelCheckException",
    );
    expect((await ir(`@service namespace S; model Req { name: string }`)).modelCheckException).toBeUndefined();
  });
});
