import { buildApiIR, loadSseLibraries } from "@abhigyakrishna/tspgen-core";
import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { transformToKotlin } from "../src/transform/index.js";
import { emitter, SseTester, Tester } from "./tester.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

const spec = `
  @service namespace S;
  model UserConnect { username: string }
  model Note { text: string }

  /** Channel events */
  @events union ChannelEvents {
    /** A user joined */
    userConnect: UserConnect,
    note: Note,
    @Events.contentType("text/plain") string: string,
    seen: utcDateTime,
    @Events.contentType("text/plain") @terminalEvent "[done]",
  }

  @route("/c") op subscribe(): SSEStream<ChannelEvents>;
`;

const SSE = await loadSseLibraries();

function kotlinIR(program: Parameters<typeof buildApiIR>[0]) {
  return transformToKotlin(program, buildApiIR(program, { sse: SSE! }), { package: "com.acme", enumMemberNaming: "UPPER_SNAKE", dateTime: "java.time" });
}

describe("kotlin server-sent events", () => {
  it("emits an @events union as a sealed interface of event classes", async () => {
    const result = await SseTester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme" }).compile(spec);
    expect(result.outputs["models/com/acme/models/ChannelEvents.kt"]).toBe(`${HEADER}
package com.acme.models

import java.time.Instant

/**
 * Channel events
 */
sealed interface ChannelEvents {
    /**
     * A user joined
     *
     * Sent as \`event: userConnect\`.
     */
    data class UserConnectEvent(val data: UserConnect) : ChannelEvents

    /**
     * Sent as \`event: note\`.
     */
    data class NoteEvent(val data: Note) : ChannelEvents

    /**
     * Sent as \`event: string\`.
     */
    data class StringEvent(val data: String) : ChannelEvents

    /**
     * Sent as \`event: seen\`.
     */
    data class Seen(val data: Instant) : ChannelEvents

    /**
     * Sent as \`event: message\`, \`data: [done]\`; ends the stream.
     */
    data object Done : ChannelEvents
}
`);
    // A java.time payload is encoded with the models' Json: its serializer is generated.
    expect(result.outputs["models/com/acme/models/ModelSerializers.kt"]).toContain("object InstantSerializer");
    expect(result.outputs["models/com/acme/models/SseMessage.kt"]).toBeUndefined();
  });

  it("returns a Flow of the events type from streaming operations", async () => {
    const { program } = await SseTester.compile(spec);
    const [op] = kotlinIR(program).services[0].groups[0].operations;
    expect(op.result).toMatchObject({
      kind: "single",
      type: { text: "Flow<ChannelEvents>", imports: ["kotlinx.coroutines.flow.Flow", "com.acme.models.ChannelEvents"] },
      status: 200,
      stream: { type: { text: "ChannelEvents" }, events: { kind: "events", name: "ChannelEvents" } },
    });
    const { events } = (op.result as { stream: { events: { events: unknown[] } } }).stream.events;
    expect(events).toEqual([
      { name: "UserConnectEvent", event: "userConnect", data: expect.objectContaining({ text: "UserConnect" }), json: true, terminal: false, docs: "A user joined" },
      { name: "NoteEvent", event: "note", data: expect.objectContaining({ text: "Note" }), json: true, terminal: false },
      { name: "StringEvent", event: "string", data: expect.objectContaining({ text: "String" }), json: false, terminal: false },
      { name: "Seen", event: "seen", data: expect.objectContaining({ text: "Instant" }), json: true, terminal: false },
      { name: "Done", event: "message", literal: "[done]", json: false, terminal: true },
    ]);
  });

  it("names unnamed events after their literal or event name and JSON-encodes JSON literals", async () => {
    const { program } = await SseTester.compile(`
      @service namespace S;
      @events union Ticks {
        int32,
        "[DONE]",
        @Events.contentType("text/plain") 42,
        @Events.contentType("application/json") "json",
      }
      @route("/t") op ticks(): SSEStream<Ticks>;
    `);
    const decl = kotlinIR(program).declarations.find((d) => d.name === "Ticks");
    expect(decl?.kind === "events" && decl.events.map((e) => [e.name, e.literal, e.json])).toEqual([
      ["Message", undefined, true],
      ["DONE", "[DONE]", false],
      ["MessageEvent", "42", false],
      ["Json", '"json"', true],
    ]);
  });

  it("streams untyped events as SseMessage, emitted once", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      @route("/a") op a(): { @header contentType: "text/event-stream"; @body body: string };
      @route("/b") op b(): { @header contentType: "text/event-stream"; @body body: string };
    `);
    expect(outputs["models/com/acme/models/SseMessage.kt"]).toBe(`${HEADER}
package com.acme.models

/**
 * One server-sent event of an untyped event stream: its \`event:\` name (absent for the default "message" type),
 * \`data:\` lines (joined with "\\n") and \`id:\`.
 */
data class SseMessage(
    val data: String,
    val event: String? = null,
    val id: String? = null,
)
`);
  });

  it("reports a model generated as SseMessage when untyped streams need it", async () => {
    const [, diagnostics] = await Tester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme" }).compileAndDiagnose(`
      @service namespace S;
      model SseMessage { text: string }
      @route("/m") op m(): SseMessage;
      @route("/a") op a(): { @header contentType: "text/event-stream"; @body body: string };
    `);
    expectDiagnostics(diagnostics.filter((d) => d.code.endsWith("sse-message-conflict")), {
      code: "@abhigyakrishna/tspgen-kotlin/sse-message-conflict",
      message: /Model 'S.SseMessage' is generated as 'com.acme.models.SseMessage'/,
    });
  });

  it("generates nothing new for APIs without streams", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Pet { name: string }
      @route("/p") op get(): Pet;
    `);
    expect(Object.keys(outputs).filter((k) => k.endsWith(".kt")).sort()).toEqual([
      "models/com/acme/api/ApiException.kt",
      "models/com/acme/models/Pet.kt",
    ]);
  });
});
