import { buildApiIR } from "@abhigyakrishna/tspgen-core";
import { expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { transformToKotlin } from "../src/transform/index.js";
import { emitter, Tester } from "./tester.js";

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

const spec = `
  @service namespace S;
  model Meta { title: string }
  model UploadRequest {
    name: HttpPart<string>;
    count?: HttpPart<int32>;
    meta: HttpPart<Meta>;
    avatar: HttpPart<File>;
    photos: HttpPart<File<"image/png">>[];
    @encodedName("application/json", "display_name") displayName?: HttpPart<string>;
  }
  @route("/u") interface U {
    @post upload(@header contentType: "multipart/form-data", @multipartBody body: UploadRequest): void;
    @post @route("raw") raw(@bodyRoot file: File<"image/png">): void;
  }
`;

describe("kotlin uploads", () => {
  it("emits HttpFile once in the models package", async () => {
    const { outputs } = await emitter().compile(spec);
    expect(outputs["models/com/acme/models/HttpFile.kt"]).toBe(`${HEADER}
package com.acme.models

/**
 * A file sent as an HTTP body or a multipart part: its bytes plus the optional filename and content type.
 */
class HttpFile(
    val filename: String?,
    val contentType: String?,
    val bytes: ByteArray,
) {
    override fun equals(other: Any?): Boolean =
        other is HttpFile && filename == other.filename && contentType == other.contentType && bytes.contentEquals(other.bytes)

    override fun hashCode(): Int = 31 * (31 * filename.hashCode() + contentType.hashCode()) + bytes.contentHashCode()

    override fun toString(): String = "HttpFile(filename=$filename, contentType=$contentType, size=\${bytes.size})"
}
`);
  });

  it("emits the multipart body model as a plain class with HttpFile parts", async () => {
    const { outputs } = await emitter().compile(spec);
    expect(outputs["models/com/acme/models/UploadRequest.kt"]).toBe(`${HEADER}
package com.acme.models

data class UploadRequest(
    val name: String,
    val count: Int? = null,
    val meta: Meta,
    val avatar: HttpFile,
    val photos: List<HttpFile>,
    val displayName: String? = null,
)
`);
    expect(outputs["models/com/acme/models/Meta.kt"]).toContain("@Serializable\ndata class Meta(");
  });

  it("emits no HttpFile without file uses", async () => {
    const { outputs } = await emitter().compile(`@service namespace S; model Pet { name: string }`);
    expect(Object.keys(outputs).some((p) => p.endsWith("/HttpFile.kt"))).toBe(false);
  });

  it("describes multipart parts and file bodies on the operation", async () => {
    const { program } = await Tester.compile(spec);
    const ir = transformToKotlin(program, buildApiIR(program), { package: "com.acme", enumMemberNaming: "UPPER_SNAKE" });
    const [upload, raw] = ir.services[0].groups[0].operations;
    expect(upload.params).toEqual([]);
    expect(upload.body).toMatchObject({ name: "body", kind: "multipart", type: { text: "UploadRequest" } });
    expect(upload.body?.parts?.map((p) => [p.name, p.wireName, p.kind, p.multi, p.optional, p.type.text, p.contentTypes])).toEqual([
      ["name", "name", "text", false, false, "String", ["text/plain"]],
      ["count", "count", "text", false, true, "Int", ["text/plain"]],
      ["meta", "meta", "json", false, false, "Meta", ["application/json"]],
      ["avatar", "avatar", "file", false, false, "HttpFile", []],
      ["photos", "photos", "file", true, false, "HttpFile", ["image/png"]],
      ["displayName", "displayName", "text", false, true, "String", ["text/plain"]],
    ]);
    expect(raw.body).toMatchObject({
      name: "file",
      kind: "file",
      type: { text: "HttpFile", imports: ["com.acme.models.HttpFile"] },
      file: { isText: false, contentTypes: ["image/png"] },
    });
    expect(ir.httpFile).toBe("com.acme.models.HttpFile");
  });

  it("maps HttpPart<bytes> to HttpFile and emits spread part bases as plain classes", async () => {
    const { outputs } = await emitter().compile(`
      @service namespace S;
      model Base { f: HttpPart<File>; }
      model Up { ...Base; blob: HttpPart<bytes>; }
      @post op up(@header contentType: "multipart/form-data", @multipartBody body: Up): void;
    `);
    expect(outputs["models/com/acme/models/Up.kt"]).toContain("data class Up(\n    val f: HttpFile,\n    val blob: HttpFile,\n)");
    expect(outputs["models/com/acme/models/Base.kt"]).not.toContain("@Serializable");
  });

  it("reports a model named HttpFile when the API uses files", async () => {
    const [, diagnostics] = await emitter().compileAndDiagnose(`
      @service namespace S;
      model HttpFile { name: string }
      @post op up(@bodyRoot file: File): void;
      @get op get(): HttpFile;
    `);
    expectDiagnostics(diagnostics, [
      { code: "@abhigyakrishna/tspgen-kotlin/http-file-conflict", message: /'S\.HttpFile'.*@Kotlin\.name/ },
      { code: "@abhigyakrishna/tspgen-core/duplicate-file" },
    ]);
  });
});
