import { resolvePath } from "@typespec/compiler";
import { createTester, expectDiagnostics } from "@typespec/compiler/testing";
import { describe, expect, it } from "vitest";
import { emitter } from "./tester.js";

const VersionedTester = createTester(resolvePath(import.meta.dirname, ".."), {
  libraries: ["@typespec/http", "@typespec/versioning", "@abhigyakrishna/tspgen-core", "@abhigyakrishna/tspgen-kotlin"],
})
  .importLibraries()
  .using("Http", "Versioning");

function versioned(options: Record<string, unknown> = {}) {
  return VersionedTester.emit("@abhigyakrishna/tspgen-kotlin", { package: "com.acme", ...options });
}

const HEADER = "// Code generated by @abhigyakrishna/tspgen-kotlin. DO NOT EDIT.";

const spec = `
  @service @versioned(Versions) namespace PetStore;
  enum Versions { v1: "2024-01-01", v2: "2024-06-01" }
  model Pet {
    id: int64;
    @renamedFrom(Versions.v2, "title") name: string;
    @added(Versions.v2) age?: int32;
    @madeOptional(Versions.v2) tag?: string;
  }
  @added(Versions.v2) model Toy { name: string }
`;

describe("versioning", () => {
  it("emits the latest version and its API_VERSION constant", async () => {
    const { outputs } = await versioned().compile(spec);
    expect(Object.keys(outputs).filter((f) => f.endsWith(".kt")).sort()).toEqual([
      "models/com/acme/models/ApiVersionConstants.kt",
      "models/com/acme/models/Pet.kt",
      "models/com/acme/models/Toy.kt",
    ]);
    expect(outputs["models/com/acme/models/ApiVersionConstants.kt"]).toBe(`${HEADER}
package com.acme.models

/**
 * Version of the PetStore API this code was generated for.
 */
const val API_VERSION: String = "2024-06-01"
`);
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain(`data class Pet(
    val id: Long,
    val name: String,
    val age: Int? = null,
    val tag: String? = null,
)`);
  });

  it("does not clash with a version enum named ApiVersion used as a parameter", async () => {
    const [{ outputs }, diagnostics] = await versioned().compileAndDiagnose(`
      @service @versioned(ApiVersion) namespace PetStore;
      enum ApiVersion { v2024: "2024-01-01", v2025: "2025-01-01" }
      model Pet { id: int64 }
      @route("/pets") op list(@query("api-version") apiVersion: ApiVersion): Pet[];
    `);
    expect(diagnostics).toEqual([]);
    expect(outputs["models/com/acme/models/ApiVersion.kt"]).toContain("enum class ApiVersion");
    expect(outputs["models/com/acme/models/ApiVersionConstants.kt"]).toContain(
      `const val API_VERSION: String = "2025-01-01"`,
    );
  });

  it("emits the version chosen by the version option", async () => {
    const { outputs } = await versioned({ version: "v1" }).compile(spec);
    expect(outputs["models/com/acme/models/Toy.kt"]).toBeUndefined();
    expect(outputs["models/com/acme/models/ApiVersionConstants.kt"]).toContain(`const val API_VERSION: String = "2024-01-01"`);
    expect(outputs["models/com/acme/models/Pet.kt"]).toContain(`data class Pet(
    val id: Long,
    val title: String,
    val tag: String,
)`);
  });

  it("names the constants after the services when several are versioned", async () => {
    const { outputs } = await versioned().compile(`
      @service @versioned(AV) namespace Alpha { enum AV { v1: "a1" } }
      @service @versioned(BV) namespace BetaApi { enum BV { v1: "b1", v2: "b2" } }
    `);
    const file = outputs["models/com/acme/models/ApiVersionConstants.kt"];
    expect(file).toContain(`const val ALPHA_API_VERSION: String = "a1"`);
    expect(file).toContain(`const val BETA_API_API_VERSION: String = "b2"`);
  });

  it("reports an unknown version", async () => {
    const [, diagnostics] = await versioned({ version: "v9" }).compileAndDiagnose(spec);
    expectDiagnostics(diagnostics, { code: "@abhigyakrishna/tspgen-core/unknown-version" });
  });

  it("emits no constant for unversioned services", async () => {
    const { outputs } = await emitter().compile(`@service namespace S; model M { a: string }`);
    expect(Object.keys(outputs).some((f) => f.endsWith("ApiVersionConstants.kt"))).toBe(false);
  });
});
